/**
 * User Factory
 * Generated by BMAD testarch-automate workflow
 * Factory functions for user test data generation
 */

import { faker } from '@faker-js/faker';

export interface User {
  id?: string;
  email: string;
  name: string;
  password?: string;
  role?: 'user' | 'admin' | 'moderator';
  isActive?: boolean;
  emailVerified?: boolean;
  createdAt?: Date;
}

/**
 * Create a user with optional overrides
 * @param overrides - Partial user data to override defaults
 * @returns User object
 */
export function createUser(overrides: Partial<User> = {}): User {
  return {
    id: faker.string.uuid(),
    email: faker.internet.email(),
    name: faker.person.fullName(),
    password: faker.internet.password({ length: 12, memorable: false }),
    role: 'user',
    isActive: true,
    emailVerified: false,
    createdAt: new Date(),
    ...overrides,
  };
}

/**
 * Create an admin user
 * @param overrides - Partial user data to override defaults
 * @returns Admin user object
 */
export function createAdminUser(overrides: Partial<User> = {}): User {
  return createUser({
    role: 'admin',
    emailVerified: true,
    ...overrides,
  });
}

/**
 * Create a user with MFA enabled
 * @param overrides - Partial user data to override defaults
 * @returns User with MFA enabled
 */
export function createMFAUser(overrides: Partial<User> = {}): User {
  return createUser({
    emailVerified: true,
    ...overrides,
  });
}

/**
 * Create multiple users
 * @param count - Number of users to create
 * @param overrides - Partial user data to apply to all
 * @returns Array of user objects
 */
export function createUsers(count: number, overrides: Partial<User> = {}): User[] {
  return Array.from({ length: count }, () => createUser(overrides));
}