/**
 * Policy API Mocks
 * Mock implementations for Policy Engine endpoints
 * Mitigates R-002: ML/Policy Dependency Risk
 *
 * Generated by BMAD ATDD workflow
 */

import { Page } from '@playwright/test';

export type PolicyGates = {
  confidenceGate: 'passed' | 'failed';
  edgeGate: 'passed' | 'failed';
  driftGate: 'passed' | 'failed';
  hardStopGate: 'passed' | 'failed';
};

export type PolicyEvaluationRequest = {
  modelOutputs: {
    winner: string;
    confidence: number;
    edge: number;
    drift?: number;
  };
};

export type PolicyEvaluationResponse = {
  status: 'Pick' | 'No-Bet' | 'Hard-Stop';
  gates: PolicyGates;
  rationale: string;
};

/**
 * Mock Policy API responses
 * Usage: await mockPolicyApi(page);
 */
export async function mockPolicyApi(page: Page) {
  await page.route('**/api/policy/evaluate', async (route) => {
    const request = await route.request();
    const postData = await request.postDataJSON() as PolicyEvaluationRequest;
    const { modelOutputs } = postData;

    // Evaluate gates based on thresholds
    const gates: PolicyGates = {
      confidenceGate: modelOutputs.confidence >= 0.60 ? 'passed' : 'failed',
      edgeGate: modelOutputs.edge >= 0.03 ? 'passed' : 'failed',
      driftGate: (modelOutputs.drift || 0) <= 0.15 ? 'passed' : 'failed',
      hardStopGate: 'passed', // Default, override for hard-stop test
    };

    // Determine status
    let status: 'Pick' | 'No-Bet' | 'Hard-Stop' = 'Pick';
    let rationale = 'All gates passed';

    if (gates.hardStopGate === 'failed') {
      status = 'Hard-Stop';
      rationale = 'Critical policy violation detected';
    } else if (gates.confidenceGate === 'failed') {
      status = 'No-Bet';
      rationale = `Confidence below threshold (${modelOutputs.confidence} < 0.60)`;
    } else if (gates.edgeGate === 'failed') {
      status = 'No-Bet';
      rationale = `Edge below threshold (${modelOutputs.edge} < 0.03)`;
    } else if (gates.driftGate === 'failed') {
      status = 'No-Bet';
      rationale = `Drift above threshold (${modelOutputs.drift} > 0.15)`;
    }

    const response: PolicyEvaluationResponse = {
      status,
      gates,
      rationale,
    };

    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(response),
    });
  });
}

/**
 * Mock Decision API with Hard-Stop enforcement
 * Usage: await mockDecisionApi(page);
 */
export async function mockDecisionApi(page: Page) {
  // POST /api/v1/decisions - Create decision
  await page.route('**/api/v1/decisions', async (route) => {
    const request = await route.request();
    
    if (request.method() === 'POST') {
      const body = await request.postDataJSON();
      
      // Validate required fields
      if (!body.matchId || !body.status) {
        await route.fulfill({
          status: 400,
          contentType: 'application/json',
          body: JSON.stringify({ error: 'Missing required fields' }),
        });
        return;
      }

      // Generate IDs
      const decision = {
        id: `dec-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        traceId: `trace-${Date.now()}`,
        createdAt: new Date().toISOString(),
        ...body,
      };

      await route.fulfill({
        status: 201,
        contentType: 'application/json',
        body: JSON.stringify(decision),
      });
    }
  });

  // POST /api/v1/decisions/publish - Publish decision
  await page.route('**/api/v1/decisions/publish', async (route) => {
    const request = await route.request();
    
    if (request.method() === 'POST') {
      const body = await request.postDataJSON();
      const decisionId = body?.decisionId;

      // Mock: Get decision and check policy gates
      // In real implementation, this would query the database
      const isHardStop = decisionId?.includes('hardstop');

      if (isHardStop) {
        await route.fulfill({
          status: 403,
          contentType: 'application/json',
          body: JSON.stringify({
            error: 'Hard-Stop violation - publication blocked',
            violation: 'critical_policy_violation',
            decisionId,
          }),
        });
        return;
      }

      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          published: true,
          decisionId,
          publishedAt: new Date().toISOString(),
        }),
      });
    }
  });
}

/**
 * Mock Hard-Stop scenario
 * Usage: await mockHardStopScenario(page);
 */
export async function mockHardStopScenario(page: Page) {
  await page.route('**/api/policy/evaluate', async (route) => {
    const response: PolicyEvaluationResponse = {
      status: 'Hard-Stop',
      gates: {
        confidenceGate: 'passed',
        edgeGate: 'passed',
        driftGate: 'passed',
        hardStopGate: 'failed',
      },
      rationale: 'Critical policy violation detected',
    };

    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(response),
    });
  });

  await page.route('**/api/v1/decisions/publish', async (route) => {
    await route.fulfill({
      status: 403,
      contentType: 'application/json',
      body: JSON.stringify({
        error: 'Hard-Stop violation - publication blocked',
        violation: 'critical_policy_violation',
      }),
    });
  });
}

/**
 * Setup all policy mocks
 * Usage: await setupPolicyMocks(page);
 */
export async function setupPolicyMocks(page: Page) {
  await mockPolicyApi(page);
  await mockDecisionApi(page);
}
