import { test, expect } from '../support/merged-fixtures';

/**
 * Admin RBAC E2E User Journey Tests
 * Generated by BMAD testarch-automate workflow
 *
 * Tags: @p0 @p1 @admin @rbac @journey @e2e
 */

test.describe('Admin RBAC User Journey @admin @rbac @journey @e2e', () => {
  test.describe('User Management @p0', () => {
    test('[P0] should access admin users page with proper role', async ({ page }) => {
      await page.goto('/admin/users');

      // Check for admin access or redirect
      const isUsersPage = await page.getByRole('heading', { name: /users|user management/i }).isVisible().catch(() => false);
      const isTableVisible = await page.locator('table').first().isVisible().catch(() => false);
      const isUnauthorized = await page.getByText(/unauthorized|access denied|403/i).isVisible().catch(() => false);

      expect(isUsersPage || isTableVisible || isUnauthorized).toBe(true);
    });

    test('[P1] should view user details', async ({ page }) => {
      await page.goto('/admin/users');

      // Check if user list is visible
      const userRow = page.locator('table tbody tr').first();
      if (await userRow.isVisible().catch(() => false)) {
        // Click on first user
        const viewLink = userRow.getByRole('link', { name: /view|edit|details/i }).first();
        if (await viewLink.isVisible().catch(() => false)) {
          await viewLink.click();
          await expect(page).toHaveURL(/user|details/);
        }
      }
    });

    test('[P1] should show role assignment interface', async ({ page }) => {
      await page.goto('/admin/users');

      // Look for role-related elements
      const roleSelect = page.getByLabel(/role/i).first();
      const roleColumn = page.getByText(/admin|user|role/i).first();
      const roleButton = page.getByRole('button', { name: /role|permissions/i }).first();

      if (await roleSelect.isVisible().catch(() => false) ||
          await roleColumn.isVisible().catch(() => false) ||
          await roleButton.isVisible().catch(() => false)) {
        expect(true).toBe(true); // Role UI present
      }
    });
  });

  test.describe('RBAC Enforcement @p0', () => {
    test('[P0] should redirect non-admin users from admin pages', async ({ page }) => {
      // Try accessing admin as regular user
      await page.goto('/admin/users');

      // Check for redirect to login or dashboard
      const currentUrl = page.url();
      const isRedirected = currentUrl.includes('login') || currentUrl.includes('dashboard') || currentUrl.includes('unauthorized');

      if (isRedirected) {
        expect(isRedirected).toBe(true);
      } else {
        // If not redirected, verify unauthorized message
        const isUnauthorized = await page.getByText(/unauthorized|access denied|forbidden/i).isVisible().catch(() => false);
        expect(isUnauthorized).toBe(true);
      }
    });

    test('[P1] should show permission-based UI elements', async ({ page }) => {
      await page.goto('/dashboard');

      // Look for admin link/button
      const adminLink = page.getByRole('link', { name: /admin|settings|manage/i });
      const adminMenu = page.getByText(/admin|management/i).first();

      // Admin elements may or may not be visible based on role
      const hasAdminAccess = await adminLink.isVisible().catch(() => false) ||
                            await adminMenu.isVisible().catch(() => false);

      // Just verify page loads correctly
      await expect(page.locator('body')).toBeVisible();
    });
  });

  test.describe('Audit Trail @p2', () => {
    test('[P2] should view audit trail if available', async ({ page }) => {
      await page.goto('/admin/audit');

      const hasAuditLog = await page.getByRole('heading', { name: /audit|log|history/i }).isVisible().catch(() => false);
      const isUnauthorized = await page.getByText(/unauthorized/i).isVisible().catch(() => false);

      expect(hasAuditLog || isUnauthorized).toBe(true);
    });
  });
});