/**
 * Admin RBAC Flows E2E Tests
 * Tests for admin user journeys and RBAC-protected flows
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P1 (High)
 */

import { test, expect } from '../support/merged-fixtures';
import { createUser, createAdminUser } from '../support/factories';

test.describe('Admin RBAC Flows - P1 @p1 @e2e @admin @rbac', () => {
  test('[P0] should allow admin to access dashboard', async ({ page }) => {
    // Given admin user is logged in
    const adminCreds = {
      email: 'admin@example.com',
      password: 'admin123',
    };

    // When logging in
    await page.goto('/login');
    await page.getByRole('textbox', { name: /email/i }).fill(adminCreds.email);
    await page.getByRole('textbox', { name: /password/i }).fill(adminCreds.password);
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();

    // Then should be redirected to dashboard
    await expect(page).toHaveURL(/\/dashboard/);

    // And should see admin-specific elements
    await expect(page.getByText(/admin|dashboard/i)).toBeVisible();
  });

  test('[P0] should block regular user from admin-only areas', async ({ page }) => {
    // Given regular user is logged in
    const userCreds = {
      email: 'test@example.com',
      password: 'testpassword123',
    };

    // When logging in as regular user
    await page.goto('/login');
    await page.getByRole('textbox', { name: /email/i }).fill(userCreds.email);
    await page.getByRole('textbox', { name: /password/i }).fill(userCreds.password);
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();

    // Then should be redirected to regular dashboard
    await expect(page).toHaveURL(/\/dashboard/);

    // And should NOT see admin elements
    await expect(page.getByText(/admin panel|user management/i)).not.toBeVisible();
  });

  test('[P1] should display user role in navigation', async ({ page }) => {
    // Given admin is logged in
    await page.goto('/login');
    await page.getByRole('textbox', { name: /email/i }).fill('admin@example.com');
    await page.getByRole('textbox', { name: /password/i }).fill('admin123');
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();

    // Then should display admin role in UI
    await expect(page.getByText(/admin|administrator/i)).toBeVisible();
  });

  test('[P1] should show role-appropriate navigation items', async ({ page }) => {
    // Given user is logged in
    await page.goto('/login');
    await page.getByRole('textbox', { name: /email/i }).fill('test@example.com');
    await page.getByRole('textbox', { name: /password/i }).fill('testpassword123');
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();

    // Then should see navigation appropriate for user role
    await expect(page.getByRole('navigation')).toBeVisible();
    await expect(page.getByText(/dashboard\/picks|dashboard|home/i)).toBeVisible();
  });

  test('[P1] should redirect unauthorized users from protected routes', async ({ page }) => {
    // Given user is not logged in
    await page.context().clearCookies();

    // When attempting to access protected route directly
    await page.goto('/dashboard/picks');

    // Then should be redirected to login
    await expect(page).toHaveURL(/\/login/);
  });

  test('[P2] should preserve role after page refresh', async ({ page }) => {
    // Given admin is logged in
    await page.goto('/login');
    await page.getByRole('textbox', { name: /email/i }).fill('admin@example.com');
    await page.getByRole('textbox', { name: /password/i }).fill('admin123');
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();
    await expect(page).toHaveURL(/\/dashboard/);

    // When refreshing the page
    await page.reload();

    // Then should still be authenticated with admin role
    await expect(page).toHaveURL(/\/dashboard/);
    await expect(page.getByText(/admin/i)).toBeVisible();
  });

  test('[P2] should show logout button for authenticated users', async ({ page }) => {
    // Given user is logged in
    await page.goto('/login');
    await page.getByRole('textbox', { name: /email/i }).fill('test@example.com');
    await page.getByRole('textbox', { name: /password/i }).fill('testpassword123');
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();

    // Then should see logout option
    await expect(page.getByRole('button', { name: /logout|sign out/i })).toBeVisible();
  });

  test('[P2] should clear session on logout', async ({ page }) => {
    // Given user is logged in
    await page.goto('/login');
    await page.getByRole('textbox', { name: /email/i }).fill('test@example.com');
    await page.getByRole('textbox', { name: /password/i }).fill('testpassword123');
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();
    await expect(page).toHaveURL(/\/dashboard/);

    // When clicking logout
    await page.getByRole('button', { name: /logout|sign out/i }).click();

    // Then should be redirected to login
    await expect(page).toHaveURL(/\/login/);

    // And should not be able to access protected routes
    await page.goto('/dashboard');
    await expect(page).toHaveURL(/\/login/);
  });

  test('[P2] should handle login form validation', async ({ page }) => {
    // Given empty login form
    await page.goto('/login');

    // When submitting empty form
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();

    // Then should show validation errors
    await expect(page.getByText(/required|email|password/i)).toBeVisible();
  });

  test('[P3] should show error for invalid credentials', async ({ page }) => {
    // Given login page
    await page.goto('/login');

    // When entering invalid credentials
    await page.getByRole('textbox', { name: /email/i }).fill('wrong@example.com');
    await page.getByRole('textbox', { name: /password/i }).fill('wrongpassword');
    await page.getByRole('button', { name: /sign in|login|submit/i }).click();

    // Then should show error message
    await expect(page.getByText(/invalid|error|failed/i)).toBeVisible();
    await expect(page).toHaveURL(/\/login/);
  });

  test('[P3] should have accessible login form', async ({ page }) => {
    // Given login page
    await page.goto('/login');

    // Then form should have proper labels and roles
    await expect(page.getByRole('textbox', { name: /email/i })).toBeVisible();
    await expect(page.getByRole('textbox', { name: /password/i })).toBeVisible();
    await expect(page.getByRole('button', { name: /sign in|login/i })).toBeVisible();
  });
});
