/**
 * Authentication Tests
 * Tests for login and protected routes
 *
 * Generated by BMAD testarch-framework workflow
 */

import { test, expect } from '../support/merged-fixtures';

test.describe('Authentication', () => {
  test('should login with valid credentials', async ({ api }) => {
    // Given valid credentials
    const credentials = {
      email: 'test@example.com',
      password: 'testpassword123',
    };

    // When logging in via API
    const response = await api.post('/api/auth/login', credentials);

    // Then the response should be successful
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.token).toBeDefined();
    expect(body.user.email).toBe(credentials.email);
  });

  test('should reject invalid credentials', async ({ api }) => {
    // Given invalid credentials
    const credentials = {
      email: 'test@example.com',
      password: 'wrongpassword',
    };

    // When logging in
    const response = await api.post('/api/auth/login', credentials);

    // Then the response should be unauthorized
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error).toBe('Invalid credentials');
  });

  test('should access protected endpoint with token', async ({ api }) => {
    // Given a logged-in user
    const loginResponse = await api.post('/api/auth/login', {
      email: 'test@example.com',
      password: 'testpassword123',
    });
    const { token } = await loginResponse.json();

    // When accessing protected endpoint
    const response = await api.get('/api/auth/me', {
      Authorization: `Bearer ${token}`,
    });

    // Then the response should be successful
    expect(response.status()).toBe(200);
  });

  test('should reject unauthenticated requests', async ({ api }) => {
    // When accessing protected endpoint without token
    const response = await api.get('/api/auth/me');

    // Then the response should be unauthorized
    expect(response.status()).toBe(401);
  });
});
