/**
 * Authentication Tests
 * Tests for login and protected routes
 *
 * Generated by BMAD testarch-framework workflow
 * Enhanced with priority tags for selective execution
 *
 * Tags:
 * - @p0: Critical path (auth failures block all users)
 * - @p1: High priority (important flows)
 * - @smoke: Smoke tests (run on every commit)
 */

import { test, expect } from '../support/merged-fixtures';

test.describe('Authentication @auth @smoke @p0 @p1', () => {
  test('@p0 @smoke [1.1-AUTH-001] should login with valid credentials', async ({ request }) => {
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    
    // Given valid credentials
    const credentials = {
      email: 'test@example.com',
      password: 'testpassword123',
    };

    // When logging in via API
    const response = await request.post(`${baseUrl}/api/auth/login`, { data: credentials });

    // Then the response should be successful
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.token).toBeDefined();
    expect(body.user.email).toBe(credentials.email);
  });

  test('@p0 @security [1.1-AUTH-002] should reject invalid credentials', async ({ request }) => {
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    
    // Given invalid credentials
    const credentials = {
      email: 'test@example.com',
      password: 'wrongpassword',
    };

    // When logging in
    const response = await request.post(`${baseUrl}/api/auth/login`, { data: credentials });

    // Then the response should be unauthorized
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error).toBe('Invalid credentials');
  });

  test('@p1 @api [1.1-AUTH-003] should access protected endpoint with token', async ({ request }) => {
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    
    // Given a logged-in user
    const loginResponse = await request.post(`${baseUrl}/api/auth/login`, {
      data: {
        email: 'test@example.com',
        password: 'testpassword123',
      },
    });
    const { token } = await loginResponse.json();

    // When accessing protected endpoint
    const response = await request.get(`${baseUrl}/api/auth/me`, {
      headers: { Authorization: `Bearer ${token}` },
    });

    // Then the response should be successful
    expect(response.status()).toBe(200);
  });

  test('@p0 @security [1.1-AUTH-004] should reject unauthenticated requests', async ({ request }) => {
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    
    // When accessing protected endpoint without token
    const response = await request.get(`${baseUrl}/api/auth/me`);

    // Then the response should be unauthorized
    expect(response.status()).toBe(401);
  });
});
