import { test, expect } from '../support/merged-fixtures';
import { createUser } from '../test-utils/factories';

/**
 * Authentication E2E User Journey Tests
 * Generated by BMAD testarch-automate workflow
 *
 * Tags: @p0 @p1 @auth @journey @e2e
 */

test.describe('Authentication User Journey @auth @journey @e2e', () => {
  test.describe('Registration Flow @p0', () => {
    test('[P0] should complete full registration journey', async ({ page }) => {
      const user = createUser({ password: 'SecurePass123!' });

      // Navigate to registration
      await page.goto('/register');
      await expect(page.getByRole('heading', { name: /register|sign up/i })).toBeVisible();

      // Fill registration form
      await page.getByLabel(/email/i).fill(user.email);
      await page.getByLabel(/name|full name/i).fill(user.name);
      await page.getByLabel(/password/i).first().fill(user.password);
      await page.getByLabel(/confirm password|repeat password/i).fill(user.password);

      // Submit form
      await page.getByRole('button', { name: /register|sign up|create account/i }).click();

      // Verify redirect to dashboard or success page
      await expect(page).toHaveURL(/dashboard|login|success/);
    });

    test('[P1] should show validation errors for invalid input', async ({ page }) => {
      await page.goto('/register');

      // Submit empty form
      await page.getByRole('button', { name: /register/i }).click();

      // Verify validation messages
      await expect(page.getByText(/email is required|invalid email/i)).toBeVisible();
      await expect(page.getByText(/password is required|password must/i)).toBeVisible();
    });

    test('[P1] should show error for weak password', async ({ page }) => {
      const user = createUser();

      await page.goto('/register');
      await page.getByLabel(/email/i).fill(user.email);
      await page.getByLabel(/password/i).first().fill('123');
      await page.getByLabel(/confirm password/i).fill('123');
      await page.getByRole('button', { name: /register/i }).click();

      await expect(page.getByText(/password must be|password is too weak/i)).toBeVisible();
    });
  });

  test.describe('Login Flow @p0', () => {
    test('[P0] should login with valid credentials', async ({ page }) => {
      await page.goto('/login');
      await expect(page.getByRole('heading', { name: /login|sign in/i })).toBeVisible();

      await page.getByLabel(/email/i).fill('test@example.com');
      await page.getByLabel(/password/i).fill('testpassword123');
      await page.getByRole('button', { name: /login|sign in/i }).click();

      // Verify successful login redirect
      await expect(page).toHaveURL(/dashboard|picks/);
    });

    test('[P0] should show error for invalid credentials', async ({ page }) => {
      await page.goto('/login');

      await page.getByLabel(/email/i).fill('test@example.com');
      await page.getByLabel(/password/i).fill('WrongPassword123!');
      await page.getByRole('button', { name: /login/i }).click();

      await expect(page.getByText(/invalid|incorrect|wrong/i)).toBeVisible();
      await expect(page).toHaveURL(/login/);
    });

    test('[P1] should navigate to register page', async ({ page }) => {
      await page.goto('/login');

      const registerLink = page.getByRole('link', { name: /register|sign up|create account/i });
      if (await registerLink.isVisible().catch(() => false)) {
        await registerLink.click();
        await expect(page).toHaveURL(/register/);
      }
    });
  });

  test.describe('MFA Flow @p1', () => {
    test('[P1] should complete MFA verification during login', async ({ page }) => {
      await page.goto('/login');
      
      // Login with MFA-enabled user
      await page.getByLabel(/email/i).fill('mfa-user@example.com');
      await page.getByLabel(/password/i).fill('SecurePass123!');
      await page.getByRole('button', { name: /login/i }).click();

      // Verify MFA prompt
      await expect(page.getByText(/verification code|mfa|authenticator/i)).toBeVisible();

      // Enter MFA code
      await page.getByLabel(/code|token/i).fill('123456');
      await page.getByRole('button', { name: /verify|submit/i }).click();

      // Verify redirect after MFA
      await expect(page).toHaveURL(/dashboard|picks/);
    });
  });
});