/**
 * Dashboard Picks E2E Tests
 * Tests for the picks dashboard page
 *
 * Generated by BMAD testarch-framework workflow
 * Pattern: Given/When/Then with data-testid selectors
 */

import { test, expect } from '../support/merged-fixtures';
import { createDecision, createMatch } from '../support/factories';

test.describe('Dashboard Picks', () => {
  test.beforeEach(async ({ page }) => {
    // Given the user is on the dashboard
    await page.goto('/dashboard/picks');
  });

  test('should display picks list', async ({ page }) => {
    // Then the picks list should be visible
    await expect(page.getByTestId('picks-list')).toBeVisible();
  });

  test('should filter picks by date', async ({ page }) => {
    // When the user selects a date filter
    await page.getByTestId('date-filter').click();
    await page.getByTestId('date-today').click();

    // Then only today's picks should be displayed
    await expect(page.getByTestId('filter-applied')).toContainText('Today');
  });

  test('should view pick details', async ({ page }) => {
    // Given there are picks available
    const firstPick = page.getByTestId('pick-card').first();
    await expect(firstPick).toBeVisible();

    // When the user clicks on a pick
    await firstPick.click();

    // Then the pick details should be displayed
    await expect(page.getByTestId('pick-detail-modal')).toBeVisible();
    await expect(page.getByTestId('pick-rationale')).toBeVisible();
    await expect(page.getByTestId('pick-confidence')).toBeVisible();
  });

  test('should show loading state', async ({ page }) => {
    // When the page is loading
    await page.goto('/dashboard/picks');

    // Then the loading state should be visible initially
    await expect(page.getByTestId('picks-loading')).toBeVisible();
  });

  test('should handle empty state', async ({ page }) => {
    // Given no picks are available
    // When the user visits the picks page
    await page.goto('/dashboard/picks');

    // Then an empty state message should be displayed
    await expect(page.getByTestId('picks-empty')).toBeVisible();
    await expect(page.getByTestId('picks-empty-message')).toContainText('No picks available');
  });
});

test.describe('Dashboard Picks - API Integration', () => {
  test('should create pick via API and display in UI', async ({ page, api, testDecision }) => {
    // Given a decision is created via API
    const response = await api.post('/api/decisions', testDecision);
    expect(response.ok()).toBeTruthy();

    // When the user visits the picks page
    await page.goto('/dashboard/picks');

    // Then the new pick should be visible
    await expect(page.getByTestId(`pick-${testDecision.id}`)).toBeVisible();
    await expect(page.getByTestId(`pick-status-${testDecision.id}`)).toContainText('Pick');
  });
});
