import { test, expect } from '../support/merged-fixtures';

/**
 * Dashboard and Picks User Journey E2E Tests
 * Generated by BMAD testarch-automate workflow
 *
 * Tags: @p0 @p1 @dashboard @picks @journey @e2e
 */

test.describe('Dashboard & Picks User Journey @dashboard @picks @journey @e2e', () => {
  test.describe('Dashboard Navigation @p0', () => {
    test('[P0] should navigate to dashboard and view picks', async ({ page }) => {
      // Navigate to dashboard
      await page.goto('/dashboard');

      // Verify dashboard loads
      await expect(page.getByRole('heading', { name: /dashboard|picks|nba/i })).toBeVisible();

      // Verify picks section or list
      await expect(page.locator('[data-testid="pick-card"], [data-testid="picks-list"], .pick-card').first()).toBeVisible();
    });

    test('[P0] should view pick details from dashboard', async ({ page }) => {
      await page.goto('/dashboard');

      // Wait for picks to load
      const firstPick = page.locator('[data-testid="pick-card"], .pick-card, [data-testid="decision-card"]').first();
      await expect(firstPick).toBeVisible();

      // Click on first pick
      await firstPick.click();

      // Verify navigation to detail page
      await expect(page).toHaveURL(/pick|decision/);
      await expect(page.getByRole('heading')).toBeVisible();
    });
  });

  test.describe('Picks Page @p1', () => {
    test('[P1] should view all picks on dedicated page', async ({ page }) => {
      await page.goto('/dashboard/picks');

      await expect(page.getByRole('heading', { name: /dashboard/picks|recommendations/i })).toBeVisible();
      await expect(page.locator('body')).toContainText(/pick|bet|recommendation/i);
    });

    test('[P1] should filter picks by criteria', async ({ page }) => {
      await page.goto('/dashboard/picks');

      // Look for filter controls
      const filterButton = page.getByRole('button', { name: /filter|sort/i });
      const filterSelect = page.getByLabel(/filter|sort|date/i);

      if (await filterButton.isVisible().catch(() => false)) {
        await filterButton.click();
      }

      // Apply filter if available
      if (await filterSelect.isVisible().catch(() => false)) {
        await filterSelect.selectOption('today');
        await expect(page.locator('body')).toBeVisible();
      }
    });

    test('[P2] should handle empty picks state', async ({ page }) => {
      // Navigate to picks with future date (likely empty)
      await page.goto('/dashboard/picks?date=2099-01-01');

      // Verify empty state or no picks message
      const hasEmptyState = await page.getByText(/no picks|empty|no recommendations/i).isVisible().catch(() => false);
      const hasPicks = await page.locator('[data-testid="pick-card"]').first().isVisible().catch(() => false);

      expect(hasEmptyState || hasPicks).toBe(true);
    });
  });

  test.describe('Decision Detail @p1', () => {
    test('[P1] should view decision details with rationale', async ({ page }) => {
      await page.goto('/dashboard/picks');

      // Find and click a decision
      const decisionLink = page.locator('a[href*="pick"], a[href*="decision"], [data-testid="pick-card"]').first();
      if (await decisionLink.isVisible().catch(() => false)) {
        await decisionLink.click();

        // Verify detail page elements
        await expect(page.getByRole('heading')).toBeVisible();
        await expect(page.locator('body')).toContainText(/confidence|rationale|analysis|recommendation/i);
      }
    });

    test('[P2] should navigate between decisions', async ({ page }) => {
      await page.goto('/dashboard/picks');

      // Get first decision
      const firstDecision = page.locator('[data-testid="pick-card"], .pick-card').first();
      if (await firstDecision.isVisible().catch(() => false)) {
        await firstDecision.click();

        // Look for navigation
        const nextButton = page.getByRole('button', { name: /next|→|>/i });
        if (await nextButton.isVisible().catch(() => false)) {
          await nextButton.click();
          await expect(page).toHaveURL(/pick|decision/);
        }
      }
    });
  });
});