/**
 * Error Handling E2E Tests
 * Tests for error boundaries and error pages
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P1
 * Test IDs: ERROR-E2E-001 through ERROR-E2E-006
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe('Error Handling E2E @e2e @error-handling @ux', () => {
  
  // ==========================================
  // 404 Not Found Page
  // ==========================================
  
  test.describe('404 Not Found Page', () => {
    test('[P1] [ERROR-E2E-001] should display 404 page for non-existent routes', async ({ page }) => {
      // Given: Non-existent URL
      // When: Navigate to invalid route
      await page.goto(`${BASE_URL}/this-page-does-not-exist`);

      // Then: Should show 404 page
      await expect(page.getByRole('heading', { name: /404|not.found|page.not.found/i })).toBeVisible();
      await expect(page.getByText(/page|route|not.*exist/i)).toBeVisible();
    });

    test('[P1] [ERROR-E2E-002] should provide navigation back to home', async ({ page }) => {
      // Given: 404 page displayed
      await page.goto(`${BASE_URL}/non-existent-page`);

      // Then: Should have link back to home
      const homeLink = page.getByRole('link', { name: /home|back|return/i });
      await expect(homeLink).toBeVisible();

      // When: Click home link
      await homeLink.click();

      // Then: Should navigate to home
      await expect(page).toHaveURL(`${BASE_URL}/`);
    });

    test('[P2] [ERROR-E2E-003] should maintain layout styling on 404', async ({ page }) => {
      // Given: 404 page
      await page.goto(`${BASE_URL}/non-existent`);

      // Then: Page should have proper layout
      await expect(page.locator('body')).toBeVisible();
      // Header or navigation should be present
      await expect(page.locator('nav, header, [role="banner"]')).toBeVisible();
    });
  });

  // ==========================================
  // Global Error Boundary
  // ==========================================
  
  test.describe('Error Boundary', () => {
    test('[P1] [ERROR-E2E-004] should display error page on runtime errors', async ({ page }) => {
      // Given: Page with error
      // Navigate to error test page if available
      await page.goto(`${BASE_URL}/error-test`).catch(() => {});
      
      // Check if error boundary is shown
      const errorHeading = page.getByRole('heading', { name: /error|something.went.wrong/i });
      if (await errorHeading.isVisible().catch(() => false)) {
        await expect(errorHeading).toBeVisible();
        await expect(page.getByText(/try.again|reload|refresh/i)).toBeVisible();
      }
    });

    test('[P2] [ERROR-E2E-005] should provide reload option on error', async ({ page }) => {
      // Given: Error page displayed
      await page.goto(`${BASE_URL}/error-test`).catch(() => {});
      
      const reloadButton = page.getByRole('button', { name: /reload|refresh|try.again/i });
      if (await reloadButton.isVisible().catch(() => false)) {
        await expect(reloadButton).toBeVisible();
      }
    });

    test('[P2] [ERROR-E2E-006] should handle API errors gracefully', async ({ page }) => {
      // Given: Page that makes API calls
      await page.goto(`${BASE_URL}/dashboard/picks`);
      
      // Wait for any error messages
      const errorMessage = page.getByRole('alert') 
        .or(page.getByText(/error|failed|unavailable/i))
        .first();
      
      // If error shown, verify it's user-friendly
      if (await errorMessage.isVisible().catch(() => false)) {
        const text = await errorMessage.textContent();
        expect(text).not.toContain('Internal Server Error'); // Should be user-friendly
      }
    });
  });
});
