/**
 * Home Page E2E Tests
 * Tests for the landing page and navigation
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P1 (High)
 */

import { test, expect } from '../support/merged-fixtures';

test.describe('Home Page - P1 @p1 @e2e @home @navigation', () => {
  test('[P0] should display home page', async ({ page }) => {
    // When visiting the home page
    await page.goto('/');

    // Then the page should load successfully
    await expect(page).toHaveURL('/');
    await expect(page.getByRole('heading', { name: /NBA Analyst/i })).toBeVisible();
  });

  test('[P0] should navigate to dashboard from home', async ({ page }) => {
    // Given the user is on the home page
    await page.goto('/');
    
    // Wait for navigation to be ready
    await page.waitForSelector('[data-testid="nav-dashboard"]', { timeout: 10000 });

    // When clicking the dashboard link
    await page.getByTestId('nav-dashboard').click();

    // Then should navigate to dashboard
    await expect(page).toHaveURL(/\/dashboard/);
    await expect(page.getByTestId('picks-list')).toBeVisible();
  });

  test('[P1] should display navigation menu', async ({ page }) => {
    // Given the user is on the home page
    await page.goto('/');
    
    // Wait for navigation to be ready
    await page.waitForSelector('[data-testid="main-navigation"]', { timeout: 10000 });

    // Then navigation elements should be visible
    await expect(page.getByTestId('main-navigation')).toBeVisible();
    await expect(page.getByTestId('nav-picks')).toBeVisible();
    await expect(page.getByTestId('nav-no-bet')).toBeVisible();
    await expect(page.getByTestId('nav-logs')).toBeVisible();
    await expect(page.getByTestId('nav-dashboard')).toBeVisible();
  });

  test('[P1] should have working page title', async ({ page }) => {
    // When visiting the home page
    await page.goto('/');

    // Then page title should be set
    await expect(page).toHaveTitle(/NBA Analyst/i);
  });

  test('[P2] should be responsive on mobile', async ({ page }) => {
    // Given a mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });

    // When visiting the home page
    await page.goto('/');

    // Then content should be visible
    await expect(page.getByRole('heading', { name: /NBA Analyst/i })).toBeVisible();
  });

  test('[P2] should load without console errors', async ({ page }) => {
    // Collect console errors
    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        consoleErrors.push(msg.text());
      }
    });

    // When visiting the home page
    await page.goto('/');
    await page.waitForLoadState('networkidle');

    // Then no console errors should exist
    expect(consoleErrors).toHaveLength(0);
  });
});
