/**
 * Logs and Replay E2E Tests
 * Tests for audit logs and decision replay
 *
 * Generated by BMAD testarch-framework workflow
 */

import { test, expect } from '../support/merged-fixtures';
import { createDecision, createRun, createMatch } from '../support/factories';

test.describe('Audit Logs', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/dashboard/logs');
  });

  test('should display decision history', async ({ page }) => {
    // Given the user is on the logs page
    // Then the decision history should be visible
    await expect(page.getByTestId('logs-timeline')).toBeVisible();
  });

  test('should filter logs by date range', async ({ page }) => {
    // When the user selects a date range
    await page.getByTestId('date-from').fill('2026-02-01');
    await page.getByTestId('date-to').fill('2026-02-12');
    await page.getByTestId('apply-filter').click();

    // Then filtered logs should be displayed
    await expect(page.getByTestId('filter-active')).toBeVisible();
  });

  test('should show log details', async ({ page }) => {
    // Given log entries exist
    const firstLog = page.getByTestId('log-entry').first();

    // When the user clicks on a log entry
    await firstLog.click();

    // Then log details should be visible
    await expect(page.getByTestId('log-detail-panel')).toBeVisible();
    await expect(page.getByTestId('log-metadata')).toBeVisible();
    await expect(page.getByTestId('log-trace-id')).toBeVisible();
  });

  test('should search logs by trace ID', async ({ page }) => {
    // When the user searches for a specific trace ID
    const traceId = 'test-trace-123';
    await page.getByTestId('trace-search').fill(traceId);
    await page.getByTestId('search-submit').click();

    // Then logs with that trace ID should be displayed
    await expect(page.getByTestId('search-results')).toContainText(traceId);
  });
});

test.describe('Decision Replay', () => {
  test('should replay a past decision', async ({ page, api }) => {
    // Given a decision exists in the system
    const match = createMatch();
    const decision = createDecision({ matchId: match.id });

    await api.post('/api/decisions', decision);

    // When the user requests a replay
    await page.goto('/dashboard/logs');
    await page.getByTestId(`replay-btn-${decision.id}`).click();

    // Then the replay modal should open
    await expect(page.getByTestId('replay-modal')).toBeVisible();
    await expect(page.getByTestId('replay-status')).toContainText('Replaying');
  });

  test('should show replay results', async ({ page }) => {
    // Given a replay is in progress
    await page.goto('/dashboard/logs');
    await page.getByTestId('replay-btn').first().click();

    // When the replay completes
    await expect(page.getByTestId('replay-complete')).toBeVisible();

    // Then the replay results should be displayed
    await expect(page.getByTestId('replay-comparison')).toBeVisible();
    await expect(page.getByTestId('original-decision')).toBeVisible();
    await expect(page.getByTestId('replayed-decision')).toBeVisible();
  });

  test('should allow investigation of contested decisions', async ({ page, api }) => {
    // Given a contested decision exists
    const decision = createDecision();

    await api.post('/api/decisions', { ...decision, contested: true });

    // When viewing contested decisions
    await page.goto('/dashboard/logs?filter=contested');

    // Then contested indicators should be visible
    await expect(page.getByTestId('contested-badge')).toBeVisible();
    await expect(page.getByTestId('investigate-btn')).toBeVisible();
  });
});

test.describe('Run History', () => {
  test('should display daily runs', async ({ page, api, testRun }) => {
    // Given runs exist in the system
    await api.post('/api/runs', testRun);

    // When viewing runs
    await page.goto('/dashboard/logs');
    await page.getByTestId('runs-tab').click();

    // Then runs should be displayed
    await expect(page.getByTestId('run-entry')).toBeVisible();
    await expect(page.getByTestId('run-status')).toContainText(testRun.status);
  });

  test('should show run details', async ({ page }) => {
    // Given runs exist
    await page.goto('/dashboard/logs');
    await page.getByTestId('runs-tab').click();

    // When clicking on a run
    await page.getByTestId('run-entry').first().click();

    // Then run details should be visible
    await expect(page.getByTestId('run-detail-panel')).toBeVisible();
    await expect(page.getByTestId('run-decisions-count')).toBeVisible();
    await expect(page.getByTestId('run-errors-count')).toBeVisible();
    await expect(page.getByTestId('run-trace-id')).toBeVisible();
  });
});

test.describe('Audit Trail Compliance', () => {
  test('should track all decisions with trace IDs', async ({ api }) => {
    // When querying the audit API
    const response = await api.get('/api/logs/audit');

    // Then all entries should have trace IDs
    expect(response.ok()).toBeTruthy();
    const body = await response.json();
    expect(body.entries).toBeDefined();
  });

  test('should support time-based queries', async ({ api }) => {
    // When querying logs with time range
    const from = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    const to = new Date().toISOString();

    const response = await api.get(`/api/logs/audit?from=${from}&to=${to}`);

    // Then results should be filtered
    expect(response.ok()).toBeTruthy();
    const body = await response.json();
    expect(body.entries).toBeDefined();
  });
});
