/**
 * Mobile Responsive Design Tests
 * Tests for mobile viewport compatibility
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P1 (High) - Mobile users represent 60%+ of traffic
 *
 * Tags:
 * - @p1: High priority (mobile experience critical)
 * - @mobile: Mobile-specific tests
 * - @responsive: Responsive design tests
 * - @ux: User experience tests
 */

import { test, expect } from '../support/merged-fixtures';

/**
 * Viewport configurations for popular mobile devices
 */
const viewports = {
  iPhoneSE: { width: 375, height: 667 },
  iPhone12: { width: 390, height: 844 },
  iPadMini: { width: 768, height: 1024 },
  Pixel5: { width: 393, height: 851 },
  SamsungS21: { width: 384, height: 854 },
};

test.describe('Mobile Responsive Design @p1 @mobile @responsive @ux', () => {
  test.describe('Login Page Mobile Viewport', () => {
    for (const [device, size] of Object.entries(viewports)) {
      test(`@p1 @mobile:${device} login page should display correctly on ${device}`, async ({ page }) => {
        // Given mobile viewport
        await page.setViewportSize(size);

        // When navigating to login
        await page.goto('/login');

        // Then elements should be visible and properly sized
        const emailInput = page.getByRole('textbox', { name: /email/i });
        const passwordInput = page.getByRole('textbox', { name: /password/i });
        const submitButton = page.getByRole('button', { name: /login|connexion/i });

        await expect(emailInput).toBeVisible();
        await expect(passwordInput).toBeVisible();
        await expect(submitButton).toBeVisible();

        // Check that form is vertically stacked (mobile layout)
        const emailBox = await emailInput.boundingBox();
        const passwordBox = await passwordInput.boundingBox();

        expect(emailBox).toBeDefined();
        expect(passwordBox).toBeDefined();

        // On mobile, elements should stack vertically
        if (emailBox && passwordBox && size.width < 768) {
          expect(passwordBox.y).toBeGreaterThan(emailBox.y);
        }
      });
    }
  });

  test.describe('Dashboard Mobile Viewport', () => {
    test('@p1 @mobile:dashboard should adapt navigation for mobile', async ({ page }) => {
      // Given authenticated user on mobile
      await page.setViewportSize(viewports.iPhone12);

      // Login first
      await page.goto('/login');
      await page.fill('[data-testid="email"]', 'test@example.com');
      await page.fill('[data-testid="password"]', 'testpassword123');
      await page.click('[data-testid="login-button"]');
      await page.waitForURL(/.*dashboard/);

      // When on mobile
      // Then navigation should be collapsed or hamburger menu
      const hamburgerMenu = page.getByRole('button', { name: /menu|navigation/i });
      const isMobileMenuPresent = await hamburgerMenu.isVisible().catch(() => false);

      if (isMobileMenuPresent) {
        await hamburgerMenu.click();
        // Menu should expand
        const nav = page.getByRole('navigation');
        await expect(nav).toBeVisible();
      }
    });

    test('@p1 @mobile:dashboard cards should stack vertically on mobile', async ({ page }) => {
      // Given authenticated user on mobile
      await page.setViewportSize(viewports.Pixel5);

      // Login and navigate to dashboard
      await page.goto('/login');
      await page.fill('[data-testid="email"]', 'test@example.com');
      await page.fill('[data-testid="password"]', 'testpassword123');
      await page.click('[data-testid="login-button"]');
      await page.waitForURL(/.*dashboard/);

      // When viewing dashboard
      await page.goto('/dashboard');

      // Then decision cards should be readable
      const cards = page.locator('[data-testid="decision-card"]').first();
      await expect(cards).toBeVisible();

      // Check card fits within viewport
      const cardBox = await cards.boundingBox();
      expect(cardBox?.width).toBeLessThanOrEqual(viewports.Pixel5.width);
    });
  });

  test.describe('Picks Page Mobile Viewport', () => {
    test('@p1 @mobile:picks should display picks list on mobile', async ({ page }) => {
      // Given mobile viewport
      await page.setViewportSize(viewports.iPhoneSE);

      // Login
      await page.goto('/login');
      await page.fill('[data-testid="email"]', 'test@example.com');
      await page.fill('[data-testid="password"]', 'testpassword123');
      await page.click('[data-testid="login-button"]');
      await page.waitForURL(/.*dashboard/);

      // When navigating to picks
      await page.goto('/dashboard/picks');

      // Then picks should be visible
      const picksHeader = page.getByRole('heading', { name: /dashboard/picks|recommendations/i });
      await expect(picksHeader).toBeVisible();

      // Content should be readable
      const content = page.locator('[data-testid="picks-content"]').first();
      const isVisible = await content.isVisible().catch(() => false);

      if (isVisible) {
        const box = await content.boundingBox();
        expect(box?.width).toBeLessThanOrEqual(viewports.iPhoneSE.width - 32); // Account for padding
      }
    });

    test('@p2 @mobile:picks detail panel should be accessible on mobile', async ({ page }) => {
      // Given mobile viewport
      await page.setViewportSize(viewports.SamsungS21);

      // Login and navigate to picks
      await page.goto('/login');
      await page.fill('[data-testid="email"]', 'test@example.com');
      await page.fill('[data-testid="password"]', 'testpassword123');
      await page.click('[data-testid="login-button"]');
      await page.waitForURL(/.*dashboard/);
      await page.goto('/dashboard/picks');

      // When clicking on a pick
      const firstPick = page.locator('[data-testid="pick-item"]').first();
      if (await firstPick.isVisible().catch(() => false)) {
        await firstPick.click();

        // Then detail panel should open (as modal or slide-over)
        const detailPanel = page.locator('[data-testid="detail-panel"], [data-testid="modal"]').first();
        await expect(detailPanel).toBeVisible();

        // Panel should fit within viewport
        const panelBox = await detailPanel.boundingBox();
        if (panelBox) {
          expect(panelBox.width).toBeLessThanOrEqual(viewports.SamsungS21.width);
        }
      }
    });
  });

  test.describe('Responsive Breakpoints', () => {
    test('@p1 @responsive should adapt layout at breakpoints', async ({ page }) => {
      // Test multiple breakpoints
      const breakpoints = [
        { name: 'mobile', width: 375, expectHamburger: true },
        { name: 'tablet', width: 768, expectHamburger: true },
        { name: 'desktop', width: 1024, expectHamburger: false },
        { name: 'large', width: 1440, expectHamburger: false },
      ];

      for (const bp of breakpoints) {
        await page.setViewportSize({ width: bp.width, height: 800 });
        await page.goto('/dashboard');

        // Check for hamburger menu presence
        const hamburger = page.getByRole('button', { name: /menu/i });
        const isHamburgerVisible = await hamburger.isVisible().catch(() => false);

        if (bp.expectHamburger) {
          expect(isHamburgerVisible).toBe(true);
        } else {
          // On desktop, navigation should be visible without hamburger
          const nav = page.getByRole('navigation');
          const isNavVisible = await nav.isVisible().catch(() => false);
          expect(isNavVisible).toBe(true);
        }
      }
    });
  });

  test.describe('Touch Interactions', () => {
    test('@p2 @mobile @touch buttons should have adequate touch targets', async ({ page }) => {
      // Given mobile viewport
      await page.setViewportSize(viewports.iPhone12);

      // Login
      await page.goto('/login');
      await page.fill('[data-testid="email"]', 'test@example.com');
      await page.fill('[data-testid="password"]', 'testpassword123');

      // Check button touch target size (minimum 44x44px recommended)
      const submitButton = page.getByRole('button', { name: /login|connexion/i });
      const box = await submitButton.boundingBox();

      if (box) {
        expect(box.width).toBeGreaterThanOrEqual(44);
        expect(box.height).toBeGreaterThanOrEqual(44);
      }
    });
  });
});

/**
 * Test execution commands:
 *
 * Run all mobile tests:
 *   npx playwright test tests/e2e/mobile-responsive.spec.ts
 *
 * Run mobile tests only:
 *   npx playwright test --grep @mobile
 *
 * Run tests for specific device:
 *   npx playwright test --grep "@mobile:iPhone"
 *
 * Run responsive tests:
 *   npx playwright test --grep @responsive
 *
 * Run P1 mobile tests:
 *   npx playwright test --grep "@p1 @mobile"
 */
