/**
 * No-Bet and Hard-Stop E2E Tests
 * Tests for policy enforcement and guardrails
 *
 * Generated by BMAD testarch-framework workflow
 */

import { test, expect } from '../support/merged-fixtures';
import { createNoBetDecision, createHardStopDecision, createMatch } from '../support/factories';

test.describe('No-Bet Flow', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/dashboard/no-bet');
  });

  test('should display no-bet recommendations', async ({ page }) => {
    // Given the user is on the no-bet page
    // Then the no-bet list should be visible
    await expect(page.getByTestId('no-bet-list')).toBeVisible();
  });

  test('should show rationale for no-bet', async ({ page, api }) => {
    // Given a no-bet decision exists
    const match = createMatch();
    const decision = createNoBetDecision({ matchId: match.id });

    await api.post('/api/decisions', decision);

    // When the user visits the no-bet page
    await page.goto('/dashboard/no-bet');

    // Then the no-bet rationale should be visible
    await expect(page.getByTestId(`no-bet-rationale-${decision.id}`)).toBeVisible();
  });

  test('should display policy gates that failed', async ({ page }) => {
    // Given there are no-bet decisions
    // When the user views a no-bet card
    const noBetCard = page.getByTestId('no-bet-card').first();
    await noBetCard.click();

    // Then the failed policy gates should be displayed
    await expect(page.getByTestId('failed-gates')).toBeVisible();
  });

  test('should allow drilling down for more info', async ({ page }) => {
    // Given a no-bet card is visible
    const noBetCard = page.getByTestId('no-bet-card').first();

    // When the user clicks "Learn more"
    await noBetCard.getByTestId('learn-more-btn').click();

    // Then the detailed explanation should be shown
    await expect(page.getByTestId('detailed-explanation')).toBeVisible();
  });
});

test.describe('Hard-Stop Flow', () => {
  test('should enforce hard-stop on policy violation', async ({ page, api }) => {
    // Given a decision with hard-stop policy violation
    const match = createMatch();
    const decision = createHardStopDecision({ matchId: match.id });

    await api.post('/api/decisions', decision);

    // When the user tries to view the pick
    await page.goto(`/dashboard/picks/${decision.id}`);

    // Then the hard-stop banner should be displayed
    await expect(page.getByTestId('hard-stop-banner')).toBeVisible();
    await expect(page.getByTestId('hard-stop-message')).toContainText('Critical policy violation');
  });

  test('should block pick publication on hard-stop', async ({ api }) => {
    // Given a decision with hard-stop
    const decision = createHardStopDecision();

    await api.post('/api/decisions', decision);

    // When attempting to publish via API
    const response = await api.post('/api/decisions/publish', { decisionId: decision.id });

    // Then the publication should be blocked
    expect(response.status()).toBe(403);
  });

  test('should show audit trail for hard-stop', async ({ page }) => {
    // Given a hard-stop decision exists
    // When the user views the decision logs
    await page.goto('/dashboard/logs');

    // Then the hard-stop event should be visible in the audit trail
    await expect(page.getByTestId('audit-log-entry')).toContainText('Hard-Stop activated');
    await expect(page.getByTestId('log-trace-id')).toBeVisible();
  });
});

test.describe('Policy Engine Integration', () => {
  test('should evaluate policy via API', async ({ api }) => {
    // When evaluating a decision against policy
    const response = await api.post('/api/policy/evaluate', {
      modelOutputs: {
        winner: 'Team A',
        confidence: 0.85,
        edge: 0.03,
      },
    });

    // Then the policy result should be returned
    expect(response.ok()).toBeTruthy();
    const body = await response.json();
    expect(body.status).toBeDefined();
    expect(body.gates).toBeDefined();
  });
});
