import { test, expect } from '../support/merged-fixtures';

/**
 * Policy Management E2E User Journey Tests
 * Generated by BMAD testarch-automate workflow
 *
 * Tags: @p0 @p1 @policy @hardstop @journey @e2e
 */

test.describe('Policy Management User Journey @policy @journey @e2e', () => {
  test.describe('Policy Status @p0', () => {
    test('[P0] should view policy status and guardrails', async ({ page }) => {
      // Navigate to policy/status page or dashboard
      await page.goto('/dashboard');

      // Look for policy/guardrail indicator
      const guardrailBanner = page.locator('[data-testid="guardrail-banner"], [data-testid="policy-status"]').first();
      const statusBadge = page.getByText(/active|blocked|limited|hard stop/i).first();

      if (await guardrailBanner.isVisible().catch(() => false)) {
        await expect(guardrailBanner).toBeVisible();
      } else if (await statusBadge.isVisible().catch(() => false)) {
        await expect(statusBadge).toBeVisible();
      }
    });

    test('[P0] should display hard stop when triggered', async ({ page }) => {
      // Navigate to no-bet page (hard stop state)
      await page.goto('/dashboard/no-bet');

      // Verify hard stop message
      await expect(page.getByText(/betting suspended|hard stop|blocked|restricted/i).first()).toBeVisible();
      await expect(page.locator('body')).toContainText(/policy|risk|limit/i);
    });
  });

  test.describe('Policy Admin @p1', () => {
    test('[P1] should access policy configuration', async ({ page }) => {
      await page.goto('/admin/policy');

      // Verify admin access or redirect
      const isAdmin = await page.getByRole('heading', { name: /policy|configuration|settings/i }).isVisible().catch(() => false);
      const isUnauthorized = await page.getByText(/unauthorized|access denied|403/i).isVisible().catch(() => false);
      const isLogin = await page.getByLabel(/password/i).isVisible().catch(() => false);

      expect(isAdmin || isUnauthorized || isLogin).toBe(true);
    });

    test('[P2] should view policy evaluation logs', async ({ page }) => {
      await page.goto('/admin/policy/logs');

      const hasLogs = await page.getByText(/evaluation|policy|log/i).first().isVisible().catch(() => false);
      const isEmpty = await page.getByText(/no logs|empty/i).isVisible().catch(() => false);
      const isUnauthorized = await page.getByText(/unauthorized/i).isVisible().catch(() => false);

      expect(hasLogs || isEmpty || isUnauthorized).toBe(true);
    });
  });

  test.describe('Policy Reset @p1', () => {
    test('[P1] should show policy reset option for admins', async ({ page }) => {
      await page.goto('/admin/policy');

      const resetButton = page.getByRole('button', { name: /reset|clear|reset hard stop/i });
      
      if (await resetButton.isVisible().catch(() => false)) {
        // Verify reset button is present (don't click - it's destructive)
        await expect(resetButton).toBeVisible();
      }
    });
  });
});