import { test, expect } from '../support/merged-fixtures';

/**
 * RGPD/Privacy E2E User Journey Tests
 * Generated by BMAD testarch-automate workflow
 *
 * Tags: @p0 @p1 @rgpd @privacy @gdpr @journey @e2e
 */

test.describe('RGPD Privacy User Journey @rgpd @privacy @journey @e2e', () => {
  test.describe('Data Export @p0', () => {
    test('[P0] should access data export page', async ({ page }) => {
      await page.goto('/settings/privacy');

      // Verify privacy settings page
      await expect(page.getByRole('heading', { name: /privacy|data|export/i }).first()).toBeVisible();
    });

    test('[P0] should initiate data export request', async ({ page }) => {
      await page.goto('/settings/privacy');

      // Look for export button
      const exportButton = page.getByRole('button', { name: /export|download.*data/i });
      
      if (await exportButton.isVisible().catch(() => false)) {
        await exportButton.click();

        // Verify confirmation or progress
        await expect(page.getByText(/export|processing|email|request/i).first()).toBeVisible();
      }
    });

    test('[P1] should show export status', async ({ page }) => {
      await page.goto('/settings/privacy');

      const statusText = page.getByText(/status|ready|processing|completed/i).first();
      if (await statusText.isVisible().catch(() => false)) {
        await expect(statusText).toBeVisible();
      }
    });
  });

  test.describe('Account Deletion @p0', () => {
    test('[P0] should access account deletion page', async ({ page }) => {
      await page.goto('/settings/privacy');

      // Look for delete account section or link
      const deleteSection = page.getByText(/delete|remove|close.*account/i).first();
      const deleteLink = page.getByRole('link', { name: /delete.*account/i });
      
      if (await deleteLink.isVisible().catch(() => false)) {
        await deleteLink.click();
      }

      await expect(page.getByRole('heading').first()).toBeVisible();
    });

    test('[P0] should show deletion confirmation dialog', async ({ page }) => {
      await page.goto('/settings/privacy');

      // Find and click delete button
      const deleteButton = page.getByRole('button', { name: /delete.*account|close.*account/i });
      
      if (await deleteButton.isVisible().catch(() => false)) {
        await deleteButton.click();

        // Verify confirmation dialog
        const confirmDialog = page.getByRole('dialog')
          .or(page.locator('[role="dialog"]'))
          .or(page.locator('body:has-text("are you sure")'));
        
        await expect(page.getByText(/confirm|sure|permanent/i).first()).toBeVisible();
      }
    });

    test('[P1] should require confirmation for deletion', async ({ page }) => {
      await page.goto('/settings/privacy');

      const deleteButton = page.getByRole('button', { name: /delete.*account/i });
      
      if (await deleteButton.isVisible().catch(() => false)) {
        await deleteButton.click();

        // Look for confirmation input
        const confirmInput = page.getByLabel(/confirm|type|password/i);
        if (await confirmInput.isVisible().catch(() => false)) {
          await confirmInput.fill('DELETE');
          
          const finalDelete = page.getByRole('button', { name: /permanently|confirm/i });
          expect(await finalDelete.isVisible().catch(() => false)).toBe(true);
        }
      }
    });
  });

  test.describe('Privacy Settings @p1', () => {
    test('[P1] should view and update privacy preferences', async ({ page }) => {
      await page.goto('/settings/privacy');

      // Look for privacy controls
      const privacyToggle = page.getByRole('switch').first()
        .or(page.locator('input[type="checkbox"]').first());
      const privacySelect = page.getByLabel(/privacy|tracking|cookies/i).first();

      if (await privacyToggle.isVisible().catch(() => false)) {
        await privacyToggle.click();
        // Verify toggle changed state
      } else if (await privacySelect.isVisible().catch(() => false)) {
        await privacySelect.selectOption('strict');
      }
    });
  });
});