/**
 * RGPD Account Deletion Flow E2E Tests
 * 
 * Coverage: Complete user account deletion journey
 * Priority: P1 - Critical RGPD compliance functionality
 * 
 * Generated by: testarch-automate workflow
 * 
 * Test Pattern: Given-When-Then with network-first pattern
 */

import { test, expect } from '@playwright/test';

test.describe('RGPD Account Deletion Flow', () => {
  // Helper to create authenticated user state
  const createAuthenticatedUser = async (page: any) => {
    // Store auth state for reuse
    await page.context().storageState({ path: 'playwright/.auth/user.json' });
  };

  test.describe('User Initiates Account Deletion', () => {
    test('[P0] should allow user to navigate to deletion settings', async ({ page }) => {
      // Given: An authenticated user on the dashboard
      await page.goto('/dashboard');

      // When: User navigates to privacy settings
      await page.getByTestId('nav-settings').click();
      await page.getByTestId('settings-privacy').click();

      // Then: Should display privacy settings page with deletion option
      await expect(page).toHaveURL(/\/settings\/privacy/);
      await expect(page.getByTestId('delete-account-button')).toBeVisible();
    });

    test('[P0] should show confirmation dialog when requesting deletion', async ({ page }) => {
      // Given: User is on privacy settings page
      await page.goto('/settings/privacy');

      // When: User clicks delete account button
      await page.getByTestId('delete-account-button').click();

      // Then: Should show confirmation dialog
      await expect(page.getByTestId('deletion-confirmation-dialog')).toBeVisible();
      await expect(page.getByText('Are you sure you want to delete your account?')).toBeVisible();
    });

    test('[P1] should require password confirmation for deletion', async ({ page }) => {
      // Given: User is on privacy settings page
      await page.goto('/settings/privacy');

      // When: User clicks delete account
      await page.getByTestId('delete-account-button').click();

      // Then: Should require password confirmation
      await expect(page.getByTestId('deletion-password-input')).toBeVisible();
      await expect(page.getByTestId('confirm-delete-button')).toBeDisabled();
    });

    test('[P1] should validate incorrect password', async ({ page }) => {
      // Given: User is on deletion confirmation dialog
      await page.goto('/settings/privacy');
      await page.getByTestId('delete-account-button').click();

      // When: User enters incorrect password
      await page.getByTestId('deletion-password-input').fill('wrong-password');
      await page.getByTestId('confirm-delete-button').click();

      // Then: Should show error message
      await expect(page.getByTestId('deletion-error')).toBeVisible();
      await expect(page.getByText('Incorrect password')).toBeVisible();
    });

    test('[P2] should allow user to cancel deletion', async ({ page }) => {
      // Given: User is on deletion confirmation dialog
      await page.goto('/settings/privacy');
      await page.getByTestId('delete-account-button').click();

      // When: User clicks cancel
      await page.getByTestId('cancel-deletion-button').click();

      // Then: Should return to privacy settings
      await expect(page.getByTestId('deletion-confirmation-dialog')).not.toBeVisible();
      await expect(page.getByTestId('delete-account-button')).toBeVisible();
    });
  });

  test.describe('Account Deletion Processing', () => {
    test('[P0] should successfully delete account with valid credentials', async ({ page }) => {
      // Given: Network interception for deletion API
      await page.route('**/api/v1/user/delete-account', async (route) => {
        await route.continue();
      });

      // And: User is on deletion confirmation dialog with correct password
      await page.goto('/settings/privacy');
      await page.getByTestId('delete-account-button').click();
      await page.getByTestId('deletion-password-input').fill('correct-password');

      // When: User confirms deletion
      await page.getByTestId('confirm-delete-button').click();

      // Then: Should show processing state
      await expect(page.getByTestId('deletion-processing')).toBeVisible();

      // And: Should redirect to homepage after successful deletion
      await expect(page).toHaveURL('/', { timeout: 10000 });
    });

    test('[P1] should show data retention information before deletion', async ({ page }) => {
      // Given: User is on deletion confirmation dialog
      await page.goto('/settings/privacy');
      await page.getByTestId('delete-account-button').click();

      // Then: Should display data retention information
      await expect(page.getByTestId('data-retention-info')).toBeVisible();
      await expect(page.getByText('Your data will be retained for')).toBeVisible();
    });

    test('[P2] should allow downloading data before deletion', async ({ page }) => {
      // Given: User is on deletion confirmation dialog
      await page.goto('/settings/privacy');
      await page.getByTestId('delete-account-button').click();

      // Then: Should show option to download data
      await expect(page.getByTestId('download-data-link')).toBeVisible();
    });
  });

  test.describe('Post-Deletion State', () => {
    test('[P1] should log out user after account deletion', async ({ page }) => {
      // Given: User has successfully deleted account
      await page.goto('/');

      // Then: Should be logged out
      await expect(page.getByTestId('login-button')).toBeVisible();
      await expect(page.getByTestId('nav-dashboard')).not.toBeVisible();
    });

    test('[P2] should show success message after deletion', async ({ page }) => {
      // Given: User is redirected after deletion
      await page.goto('/');

      // Then: Should show success message
      await expect(page.getByTestId('deletion-success-message')).toBeVisible();
      await expect(page.getByText('Account deleted successfully')).toBeVisible();
    });
  });

  test.describe('Deletion Status Check', () => {
    test('[P1] should allow user to check deletion status', async ({ page }) => {
      // Given: User navigates to deletion status page
      await page.goto('/settings/privacy/deletion-status');

      // Then: Should display deletion status
      await expect(page.getByTestId('deletion-status-panel')).toBeVisible();
      await expect(page.getByTestId('deletion-status')).toBeVisible();
    });

    test('[P2] should show pending deletion can be cancelled', async ({ page }) => {
      // Given: User has pending deletion
      await page.goto('/settings/privacy/deletion-status');

      // Then: Should show cancel option if deletion is pending
      const status = await page.getByTestId('deletion-status').textContent();
      if (status?.includes('pending')) {
        await expect(page.getByTestId('cancel-deletion-link')).toBeVisible();
      }
    });
  });

  test.describe('Cancel Deletion', () => {
    test('[P2] should allow cancelling pending deletion', async ({ page }) => {
      // Given: User has pending deletion
      await page.goto('/settings/privacy/deletion-status');

      // When: User clicks cancel deletion
      await page.getByTestId('cancel-deletion-link').click();

      // Then: Should restore account
      await expect(page.getByTestId('deletion-cancelled-message')).toBeVisible();
    });
  });
});
