/**
 * Complete User Journey E2E Tests
 * End-to-end tests for critical user flows
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P0 (Critical)
 */

import { test, expect } from '@playwright/test';
import { createDecision, createMatch } from '../support/factories';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe('Critical User Journey - P0 @p0 @e2e @journey @critical', () => {
   
  test('[P0] [1.1-JRN-001] should complete login to picks journey', async ({ page }) => {
    // Given: User is on login page
    const loginResponse = page.waitForResponse(resp => resp.url().includes('/api/auth') || resp.status() === 200);
    await page.goto('/login');
    await loginResponse;
    
    // When: User logs in with valid credentials
    await page.getByLabel(/email/i).fill('test@example.com');
    await page.getByLabel(/password/i).fill('testpassword123');
    await page.getByRole('button', { name: /sign in|login/i }).click();
    
    // Then: Should be redirected to dashboard
    await page.waitForURL(/\/dashboard/, { timeout: 10000 });
    
    // Verify we're on a dashboard page (picks, no-bet, or logs)
    const url = page.url();
    expect(url).toMatch(/\/dashboard/);
    
    // Verify page loaded with content
    const hasHeading = await page.getByRole('heading').first().isVisible().catch(() => false);
    const hasContent = await page.locator('main').isVisible().catch(() => false);
    expect(hasHeading || hasContent).toBe(true);
  });

  test('[P0] [1.1-JRN-002] should view dashboard sections', async ({ page }) => {
    // Given: Navigate directly to picks (bypass login for this test)
    const picksResponse = page.waitForResponse(resp => resp.url().includes('/api/') || resp.status() === 200);
    await page.goto('/dashboard/picks');
    await picksResponse;
    
    // Then: Should see picks page content
    const picksListVisible = await page.getByTestId('picks-list').isVisible().catch(() => false);
    const hasContent = await page.locator('main').isVisible().catch(() => false);
    expect(picksListVisible || hasContent).toBe(true);
    
    // When: Navigate to No-Bet
    const noBetResponse = page.waitForResponse(resp => resp.url().includes('/api/') || resp.status() === 200);
    await page.goto('/dashboard/no-bet');
    await noBetResponse;
    const noBetVisible = await page.getByTestId('no-bet-list').or(page.getByTestId('no-bet-empty')).isVisible().catch(() => false);
    const noBetContent = await page.locator('main').isVisible().catch(() => false);
    expect(noBetVisible || noBetContent).toBe(true);
    
    // When: Navigate to Logs
    const logsResponse = page.waitForResponse(resp => resp.url().includes('/api/') || resp.status() === 200);
    await page.goto('/dashboard/logs');
    await logsResponse;
    const logsVisible = await page.getByTestId('logs-timeline').or(page.getByTestId('logs-empty')).isVisible().catch(() => false);
    const logsContent = await page.locator('main').isVisible().catch(() => false);
    expect(logsVisible || logsContent).toBe(true);
  });

  test('[P1] [1.1-JRN-003] should handle decision workflow end-to-end', async ({ page, request }) => {
    // Given: A match and decision exist
    const match = createMatch();
    const decision = createDecision({ matchId: match.id, status: 'Pick' });

    // Create decision via API
    const response = await request.post(`${BASE_URL}/api/v1/decisions`, {
      data: decision,
      headers: { 'Content-Type': 'application/json' },
    });
    
    // Accept both 201 (created) and 200 (ok) responses
    expect([200, 201]).toContain(response.status());

    // When: User views picks page
    const picksResponse = page.waitForResponse(resp => resp.url().includes('/api/') || resp.status() === 200);
    await page.goto('/dashboard/picks');
    await picksResponse;

    // Then: Page should load successfully
    const contentVisible = await page.locator('main').isVisible().catch(() => false);
    expect(contentVisible).toBe(true);
  });

  test('[P1] [1.1-JRN-004] should navigate using navigation links if present', async ({ page }) => {
    // Given: User is on picks page
    const responsePromise = page.waitForResponse(resp => resp.url().includes('/api/') || resp.status() === 200);
    await page.goto('/dashboard/picks');
    await responsePromise;
    
    // Wait for navigation element to be present
    await expect(page.locator('[data-testid]').first()).toBeVisible();
    
    // Check if navigation elements exist
    const navNoBet = page.getByTestId('nav-no-bet');
    await expect(navNoBet).toBeVisible();
    
    // When: Click navigation link
    await navNoBet.click();
    await page.waitForResponse(resp => resp.status() === 200);
    
    // Then: Should navigate to no-bet page
    await expect(page).toHaveURL(/\/dashboard\/no-bet/);
  });
});
