/**
 * Complete User Journey E2E Tests
 * End-to-end tests for critical user flows
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P0 (Critical)
 */

import { test, expect } from '@playwright/test';
import { createDecision, createMatch, createUser } from '../support/factories';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe('Critical User Journey - P0 @p0 @e2e @journey @critical', () => {
  test('[P0] should complete login to picks journey', async ({ page }) => {
    // Given: User is on login page
    await page.goto('/login');
    
    // When: User logs in with valid credentials
    await page.getByLabel(/email/i).fill('test@example.com');
    await page.getByLabel(/password/i).fill('testpassword123');
    await page.getByRole('button', { name: /sign in|login/i }).click();
    
    // Then: Should be redirected to dashboard/picks
    await page.waitForURL(/\/dashboard/);
    await expect(page.getByTestId('picks-list')).toBeVisible({ timeout: 10000 });
    await expect(page.getByRole('heading', { name: /Picks|Dashboard/i })).toBeVisible();
  });

  test('[P0] should view dashboard sections', async ({ page }) => {
    // Given: User is logged in
    await page.goto('/dashboard/picks');
    await page.waitForLoadState('networkidle');
    
    // Then: Should see picks page
    await expect(page.getByTestId('picks-list')).toBeVisible({ timeout: 10000 });
    
    // When: Navigate to No-Bet
    await page.goto('/dashboard/no-bet');
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId('no-bet-list').or(page.getByTestId('no-bet-empty'))).toBeVisible({ timeout: 10000 });
    
    // When: Navigate to Logs
    await page.goto('/dashboard/logs');
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId('logs-timeline').or(page.getByTestId('logs-empty'))).toBeVisible({ timeout: 10000 });
  });

  test('[P1] should handle decision workflow end-to-end', async ({ page, request }) => {
    // Given: A match and decision exist
    const match = createMatch();
    const decision = createDecision({ matchId: match.id, status: 'Pick' });

    // Create decision via API
    const response = await request.post(`${BASE_URL}/api/decisions`, {
      data: decision,
      headers: { 'Content-Type': 'application/json' },
    });
    expect(response.status()).toBe(201);

    // When: User views picks page
    await page.goto('/dashboard/picks');
    await page.waitForLoadState('networkidle');

    // Then: Should see the picks list
    await expect(page.getByTestId('picks-list')).toBeVisible({ timeout: 10000 });
    
    // And: Can view no-bet section
    await page.goto('/dashboard/no-bet');
    await expect(page.getByTestId('no-bet-list').or(page.getByTestId('no-bet-empty'))).toBeVisible();

    // And: Can view logs
    await page.goto('/dashboard/logs');
    await expect(page.getByTestId('logs-timeline').or(page.getByTestId('logs-empty'))).toBeVisible();
  });

  test('[P1] should navigate using navigation links', async ({ page }) => {
    // Given: User is on picks page
    await page.goto('/dashboard/picks');
    await page.waitForLoadState('networkidle');
    
    // When: Click navigation links if they exist
    const hasNav = await page.getByTestId('nav-no-bet').count() > 0;
    
    if (hasNav) {
      await page.getByTestId('nav-no-bet').click();
      await page.waitForLoadState('networkidle');
      await expect(page).toHaveURL(/\/dashboard\/no-bet/);
      
      await page.getByTestId('nav-logs').click();
      await page.waitForLoadState('networkidle');
      await expect(page).toHaveURL(/\/dashboard\/logs/);
    } else {
      // Skip if navigation not available
      test.skip(!hasNav, 'Navigation elements not available');
    }
  });
});
