/**
 * Data Factories
 * Faker-based factories with overrides for test data generation
 *
 * Generated by BMAD testarch-framework workflow
 * Pattern: Dynamic factories with UUIDs for parallel safety
 */

import { faker } from '@faker-js/faker';

// ============================================
// User Factory
// ============================================

export type User = {
  id: string;
  email: string;
  name: string;
  role: 'user' | 'admin' | 'support' | 'ops';
  createdAt: Date;
  isActive: boolean;
  mfaEnabled?: boolean;
};

export const createUser = (overrides: Partial<User> = {}): User => ({
  id: faker.string.uuid(),
  email: faker.internet.email(),
  name: faker.person.fullName(),
  role: 'user',
  createdAt: new Date(),
  isActive: true,
  mfaEnabled: false,
  ...overrides,
});

// Specialized user factories
export const createAdminUser = (overrides: Partial<User> = {}): User =>
  createUser({ role: 'admin', ...overrides });

export const createSupportUser = (overrides: Partial<User> = {}): User =>
  createUser({ role: 'support', ...overrides });

export const createOpsUser = (overrides: Partial<User> = {}): User =>
  createUser({ role: 'ops', mfaEnabled: true, ...overrides });

// ============================================
// Decision Factory
// ============================================

export type Decision = {
  id: string;
  matchId: string;
  status: 'Pick' | 'No-Bet' | 'Hard-Stop';
  rationale: string;
  confidence: number;
  modelOutputs: {
    winner: string;
    score: string;
    overUnder: string;
  };
  policyGates: {
    confidenceGate: 'passed' | 'failed';
    edgeGate: 'passed' | 'failed';
    driftGate: 'passed' | 'failed';
    hardStopGate: 'passed' | 'failed';
  };
  traceId: string;
  createdAt: Date;
};

export const createDecision = (overrides: Partial<Decision> = {}): Decision => ({
  id: faker.string.uuid(),
  matchId: faker.string.uuid(),
  status: 'Pick',
  rationale: faker.lorem.sentence(),
  confidence: faker.number.float({ min: 0.6, max: 0.95 }),
  modelOutputs: {
    winner: faker.helpers.arrayElement(['Team A', 'Team B']),
    score: `${faker.number.int({ min: 80, max: 120 })}-${faker.number.int({ min: 80, max: 120 })}`,
    overUnder: faker.helpers.arrayElement(['Over', 'Under']),
  },
  policyGates: {
    confidenceGate: 'passed',
    edgeGate: 'passed',
    driftGate: 'passed',
    hardStopGate: 'passed',
  },
  traceId: faker.string.uuid(),
  createdAt: new Date(),
  ...overrides,
});

// Specialized decision factories
export const createNoBetDecision = (overrides: Partial<Decision> = {}): Decision =>
  createDecision({
    status: 'No-Bet',
    rationale: 'Edge too low for reliable pick',
    policyGates: {
      confidenceGate: 'passed',
      edgeGate: 'failed',
      driftGate: 'passed',
      hardStopGate: 'passed',
    },
    ...overrides,
  });

export const createHardStopDecision = (overrides: Partial<Decision> = {}): Decision =>
  createDecision({
    status: 'Hard-Stop',
    rationale: 'Critical policy violation detected',
    policyGates: {
      confidenceGate: 'passed',
      edgeGate: 'passed',
      driftGate: 'passed',
      hardStopGate: 'failed',
    },
    ...overrides,
  });

// ============================================
// Run Factory
// ============================================

export type Run = {
  id: string;
  date: Date;
  status: 'pending' | 'running' | 'completed' | 'failed';
  startedAt: Date;
  completedAt?: Date;
  decisionsCount: number;
  errorsCount: number;
  traceId: string;
  source?: string;
  failureReason?: string;
};

export const createRun = (overrides: Partial<Run> = {}): Run => ({
  id: faker.string.uuid(),
  date: new Date(),
  status: 'completed',
  startedAt: new Date(),
  completedAt: new Date(),
  decisionsCount: faker.number.int({ min: 1, max: 15 }),
  errorsCount: 0,
  traceId: faker.string.uuid(),
  ...overrides,
});

// Specialized run factories
export const createFailedRun = (overrides: Partial<Run> = {}): Run =>
  createRun({
    status: 'failed',
    completedAt: undefined,
    errorsCount: faker.number.int({ min: 1, max: 5 }),
    source: overrides.source ?? 'primary-model',
    failureReason: overrides.failureReason ?? 'timeout',
    ...overrides,
  });

export const createRunningRun = (overrides: Partial<Run> = {}): Run =>
  createRun({
    status: 'running',
    completedAt: undefined,
    ...overrides,
  });

// ============================================
// Match Factory
// ============================================

export type Match = {
  id: string;
  homeTeam: string;
  awayTeam: string;
  scheduledAt: Date;
  league: string;
  status: 'scheduled' | 'in_progress' | 'completed';
};

export const createMatch = (overrides: Partial<Match> = {}): Match => ({
  id: faker.string.uuid(),
  homeTeam: faker.helpers.arrayElement(['Lakers', 'Celtics', 'Warriors', 'Bulls', 'Heat']),
  awayTeam: faker.helpers.arrayElement(['Lakers', 'Celtics', 'Warriors', 'Bulls', 'Heat']),
  scheduledAt: faker.date.future(),
  league: 'NBA',
  status: 'scheduled',
  ...overrides,
});

// ============================================
// HardStop State Factory
// For Story 3.7 - GuardrailBanner tests
// ============================================

export type HardStopState = {
  isActive: boolean;
  triggeredAt?: string;
  triggerReason?: string;
  currentState: {
    dailyLoss: number;
    consecutiveLosses: number;
    bankrollPercent: number;
  };
  limits: {
    dailyLossLimit: number;
    consecutiveLosses: number;
    bankrollPercent: number;
  };
  recommendedAction: string;
};

export const createHardStopState = (overrides: Partial<HardStopState> = {}): HardStopState => ({
  isActive: true,
  triggeredAt: new Date().toISOString(),
  triggerReason: faker.helpers.arrayElement([
    'Daily loss limit exceeded',
    'Consecutive losses limit reached',
    'Bankroll percentage threshold crossed',
  ]),
  currentState: {
    dailyLoss: faker.number.float({ min: 500, max: 1000 }),
    consecutiveLosses: faker.number.int({ min: 3, max: 5 }),
    bankrollPercent: faker.number.float({ min: 15, max: 25 }),
  },
  limits: {
    dailyLossLimit: 500,
    consecutiveLosses: 3,
    bankrollPercent: 15,
  },
  recommendedAction: 'Pause trading and review strategy',
  ...overrides,
});

// Specialized hardstop factories
export const createInactiveHardStop = (overrides: Partial<HardStopState> = {}): HardStopState =>
  createHardStopState({
    isActive: false,
    triggerReason: undefined,
    triggeredAt: undefined,
    ...overrides,
  });

export const createResetHardStop = (overrides: Partial<HardStopState> = {}): HardStopState =>
  createHardStopState({
    isActive: false,
    triggerReason: undefined,
    triggeredAt: undefined,
    currentState: {
      dailyLoss: 0,
      consecutiveLosses: 0,
      bankrollPercent: 0,
    },
    ...overrides,
  });
