/**
 * Admin API Tests
 * Tests for Admin user management endpoints
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P0 (Security-Critical - RBAC)
 * Test IDs: ADMIN-API-001 through ADMIN-API-010
 * 
 * SKIPPED: Epic 4 not yet implemented
 * Re-enable when Epic 4 (Performance, logs et replay d'audit) is active
 */

import { test, expect } from '@playwright/test';
import { createUser, createAdminUser } from '../support/factories';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe.skip('Admin API Tests @api @admin @rbac @security @epic4', () => {
  // ==========================================
  // GET /api/v1/admin/users - List Users
  // ==========================================
  
  test.describe('GET /api/v1/admin/users', () => {
    test('[P0] [ADMIN-API-001] should allow admin to list users', async ({ request }) => {
      // Given: Admin authentication
      // When: GET users list
      const response = await request.get(`${BASE_URL}/api/v1/admin/users`, {
        headers: { 'Authorization': 'Bearer admin-token' },
      });

      // Then: Should return users list
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.users).toBeDefined();
      expect(Array.isArray(body.users)).toBe(true);
    });

    test('[P0] [ADMIN-API-002] should reject non-admin access', async ({ request }) => {
      // Given: Regular user authentication
      // When: GET users list
      const response = await request.get(`${BASE_URL}/api/v1/admin/users`, {
        headers: { 'Authorization': 'Bearer user-token' },
      });

      // Then: Should return 403 Forbidden
      expect(response.status()).toBe(403);
      const body = await response.json();
      expect(body.error).toMatch(/forbidden|unauthorized|insufficient/i);
    });

    test('[P0] [ADMIN-API-003] should reject unauthenticated requests', async ({ request }) => {
      // When: GET without authentication
      const response = await request.get(`${BASE_URL}/api/v1/admin/users`);

      // Then: Should return 401
      expect(response.status()).toBe(401);
    });

    test('[P1] [ADMIN-API-004] should support pagination', async ({ request }) => {
      // When: GET with pagination params
      const response = await request.get(`${BASE_URL}/api/v1/admin/users?page=1&limit=10`, {
        headers: { 'Authorization': 'Bearer admin-token' },
      });

      // Then: Should return paginated results
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.users).toBeDefined();
      expect(body.pagination).toBeDefined();
      expect(body.pagination.page).toBe(1);
      expect(body.pagination.limit).toBe(10);
    });
  });

  // ==========================================
  // PATCH /api/v1/admin/users/[id]/role - Change Role
  // ==========================================
  
  test.describe('PATCH /api/v1/admin/users/[id]/role', () => {
    test('[P0] [ADMIN-API-005] should allow admin to change user role', async ({ request }) => {
      // Given: Target user ID and new role
      const userId = 'user-to-promote-123';
      
      // When: PATCH role change
      const response = await request.patch(`${BASE_URL}/api/v1/admin/users/${userId}/role`, {
        data: { role: 'admin', reason: 'Promotion to admin' },
        headers: { 'Authorization': 'Bearer admin-token' },
      });

      // Then: Should successfully update role
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.success).toBe(true);
      expect(body.user.role).toBe('admin');
      expect(body.auditLog).toBeDefined();
    });

    test('[P0] [ADMIN-API-006] should reject role change without reason', async ({ request }) => {
      // Given: Target user ID
      const userId = 'user-to-promote-123';
      
      // When: PATCH without reason
      const response = await request.patch(`${BASE_URL}/api/v1/admin/users/${userId}/role`, {
        data: { role: 'admin' },
        headers: { 'Authorization': 'Bearer admin-token' },
      });

      // Then: Should require reason
      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body.error).toContain('reason');
    });

    test('[P0] [ADMIN-API-007] should reject invalid role values', async ({ request }) => {
      // Given: Target user ID
      const userId = 'user-to-promote-123';
      
      // When: PATCH with invalid role
      const response = await request.patch(`${BASE_URL}/api/v1/admin/users/${userId}/role`, {
        data: { role: 'superuser', reason: 'Invalid role test' },
        headers: { 'Authorization': 'Bearer admin-token' },
      });

      // Then: Should reject invalid role
      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body.error).toContain('role');
    });

    test('[P0] [ADMIN-API-008] should prevent self-demotion', async ({ request }) => {
      // Given: Admin trying to demote themselves
      const adminId = 'current-admin-id';
      
      // When: PATCH to demote self
      const response = await request.patch(`${BASE_URL}/api/v1/admin/users/${adminId}/role`, {
        data: { role: 'user', reason: 'Self demotion' },
        headers: { 'Authorization': 'Bearer admin-token' },
      });

      // Then: Should prevent self-demotion
      expect(response.status()).toBe(403);
      const body = await response.json();
      expect(body.error).toMatch(/cannot|self|own/i);
    });

    test('[P1] [ADMIN-API-009] should reject non-admin role changes', async ({ request }) => {
      // Given: Regular user trying to change roles
      const userId = 'target-user-123';
      
      // When: PATCH as regular user
      const response = await request.patch(`${BASE_URL}/api/v1/admin/users/${userId}/role`, {
        data: { role: 'admin', reason: 'Unauthorized promotion' },
        headers: { 'Authorization': 'Bearer user-token' },
      });

      // Then: Should return 403
      expect(response.status()).toBe(403);
    });

    test('[P1] [ADMIN-API-010] should return 404 for non-existent user', async ({ request }) => {
      // Given: Non-existent user ID
      const userId = 'non-existent-user';
      
      // When: PATCH role for non-existent user
      const response = await request.patch(`${BASE_URL}/api/v1/admin/users/${userId}/role`, {
        data: { role: 'admin', reason: 'Test' },
        headers: { 'Authorization': 'Bearer admin-token' },
      });

      // Then: Should return 404
      expect(response.status()).toBe(404);
      const body = await response.json();
      expect(body.error).toMatch(/not found|not exist/i);
    });
  });
});
