/**
 * Auth API Edge Case Tests
 * Tests for authentication error scenarios and validation
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P1 (High)
 */

import { test, expect } from '../support/merged-fixtures';

test.describe('Auth API Edge Cases - P1 @p1 @api @auth @security', () => {
  test('[P0] should reject login with missing email', async ({ api }) => {
    // Given login request without email
    const credentials = {
      password: 'testpassword123',
    };

    // When attempting to login
    const response = await api.post('/api/auth/login', credentials);

    // Then should return bad request
    expect(response.status()).toBe(400);
    const body = await response.json();
    expect(body.error).toBeDefined();
  });

  test('[P0] should reject login with missing password', async ({ api }) => {
    // Given login request without password
    const credentials = {
      email: 'test@example.com',
    };

    // When attempting to login
    const response = await api.post('/api/auth/login', credentials);

    // Then should return bad request
    expect(response.status()).toBe(400);
    const body = await response.json();
    expect(body.error).toBeDefined();
  });

  test('[P1] should reject login with empty credentials', async ({ api }) => {
    // Given empty credentials
    const credentials = {
      email: '',
      password: '',
    };

    // When attempting to login
    const response = await api.post('/api/auth/login', credentials);

    // Then should return unauthorized
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error).toContain('Invalid credentials');
  });

  test('[P1] should reject malformed authorization header', async ({ api }) => {
    // Given a malformed authorization header (no Bearer prefix)
    const response = await api.get('/api/auth/me', {
      Authorization: 'invalid-token-format',
    });

    // Then should return unauthorized
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error).toContain('Unauthorized');
  });

  test('[P1] should reject empty authorization header', async ({ api }) => {
    // Given empty authorization header
    const response = await api.get('/api/auth/me', {
      Authorization: '',
    });

    // Then should return unauthorized
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error).toContain('Unauthorized');
  });

  test('[P1] should reject request without authorization header', async ({ api }) => {
    // When accessing protected endpoint without any header
    const response = await api.get('/api/auth/me');

    // Then should return unauthorized
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error).toContain('Unauthorized');
  });

  test('[P2] should reject login with invalid email format', async ({ api }) => {
    // Given invalid email format
    const credentials = {
      email: 'not-an-email',
      password: 'testpassword123',
    };

    // When attempting to login
    const response = await api.post('/api/auth/login', credentials);

    // Then should return unauthorized
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error).toContain('Invalid credentials');
  });

  test('[P2] should handle case sensitivity in email', async ({ api }) => {
    // Given email with different case
    const credentials = {
      email: 'TEST@EXAMPLE.COM',
      password: 'testpassword123',
    };

    // When attempting to login
    const response = await api.post('/api/auth/login', credentials);

    // Then should authenticate (case insensitive)
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.token).toBeDefined();
  });
});
