import { test, expect } from '@playwright/test';
import { createUser } from '../test-utils/factories';

/**
 * Authentication API Tests - Coverage Expansion
 * Generated by BMAD testarch-automate workflow
 *
 * Tags: @p0 @p1 @auth @security @api
 */

test.describe('Authentication API @auth @api', () => {
  const baseUrl = process.env.BASE_URL || 'http://localhost:3000';

  test.describe('POST /api/auth/register @p0', () => {
    test('[P0] should register new user with valid credentials', async ({ request }) => {
      const user = createUser({ password: 'SecurePass123!' });

      const response = await request.post(`${baseUrl}/api/auth/register`, {
        data: {
          email: user.email,
          password: user.password,
          name: user.name,
        },
      });

      expect(response.status()).toBe(201);
      const body = await response.json();
      expect(body.user.id).toBeDefined();
      expect(body.user.email).toBe(user.email);
      expect(body.token).toBeDefined();
    });

    test('[P0] should reject registration with duplicate email', async ({ request }) => {
      const user = createUser({ email: 'duplicate@test.com', password: 'SecurePass123!' });

      // First registration
      await request.post(`${baseUrl}/api/auth/register`, {
        data: { email: user.email, password: user.password, name: user.name },
      });

      // Duplicate attempt
      const response = await request.post(`${baseUrl}/api/auth/register`, {
        data: { email: user.email, password: user.password, name: user.name },
      });

      expect(response.status()).toBe(409);
      const body = await response.json();
      expect(body.error).toContain('already exists');
    });

    test('[P1] should reject registration with weak password', async ({ request }) => {
      const user = createUser();

      const response = await request.post(`${baseUrl}/api/auth/register`, {
        data: {
          email: user.email,
          password: '123',
          name: user.name,
        },
      });

      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body.error).toContain('password');
    });

    test('[P1] should reject registration with invalid email', async ({ request }) => {
      const response = await request.post(`${baseUrl}/api/auth/register`, {
        data: {
          email: 'not-an-email',
          password: 'SecurePass123!',
          name: 'Test User',
        },
      });

      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body.error).toContain('email');
    });
  });

  test.describe('POST /api/auth/login @p0', () => {
    test('[P0] should login with valid credentials', async ({ request }) => {
      const user = createUser({ password: 'SecurePass123!' });

      // Register first
      await request.post(`${baseUrl}/api/auth/register`, {
        data: { email: user.email, password: user.password, name: user.name },
      });

      // Login
      const response = await request.post(`${baseUrl}/api/auth/login`, {
        data: {
          email: user.email,
          password: user.password,
        },
      });

      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.token).toBeDefined();
      expect(body.user.email).toBe(user.email);
    });

    test('[P0] should reject login with invalid password', async ({ request }) => {
      const user = createUser({ password: 'SecurePass123!' });

      await request.post(`${baseUrl}/api/auth/register`, {
        data: { email: user.email, password: user.password, name: user.name },
      });

      const response = await request.post(`${baseUrl}/api/auth/login`, {
        data: {
          email: user.email,
          password: 'WrongPassword123!',
        },
      });

      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Invalid credentials');
    });

    test('[P1] should reject login for non-existent user', async ({ request }) => {
      const response = await request.post(`${baseUrl}/api/auth/login`, {
        data: {
          email: 'nonexistent@example.com',
          password: 'AnyPassword123!',
        },
      });

      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Invalid credentials');
    });
  });

  test.describe('GET /api/auth/me @p0', () => {
    test('[P0] should return current user with valid token', async ({ request }) => {
      const user = createUser({ password: 'SecurePass123!' });

      const registerRes = await request.post(`${baseUrl}/api/auth/register`, {
        data: { email: user.email, password: user.password, name: user.name },
      });
      const { token } = await registerRes.json();

      const response = await request.get(`${baseUrl}/api/auth/me`, {
        headers: { Authorization: `Bearer ${token}` },
      });

      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.email).toBe(user.email);
      expect(body.name).toBe(user.name);
    });

    test('[P0] should reject request without token', async ({ request }) => {
      const response = await request.get(`${baseUrl}/api/auth/me`);
      expect(response.status()).toBe(401);
    });

    test('[P1] should reject request with invalid token', async ({ request }) => {
      const response = await request.get(`${baseUrl}/api/auth/me`, {
        headers: { Authorization: 'Bearer invalid-token' },
      });
      expect(response.status()).toBe(401);
    });
  });
});