/**
 * MFA API Tests
 * Tests for Multi-Factor Authentication endpoints
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P0 (Security-Critical)
 * Test IDs: MFA-API-001 through MFA-API-012
 * 
 * SKIPPED: Epic 4 not yet implemented
 * Re-enable when Epic 4 (Performance, logs et replay d'audit) is active
 */

import { test, expect } from '@playwright/test';
import { createUser, createAdminUser } from '../support/factories';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe.skip('MFA API Tests @api @mfa @security @epic4', () => {
  // ==========================================
  // POST /api/auth/mfa - Verify MFA Token
  // ==========================================
  
  test.describe('POST /api/auth/mfa - Token Verification', () => {
    test('[P0] [MFA-API-001] should reject request without authentication', async ({ request }) => {
      // Given: No authentication token
      // When: POST to MFA verification endpoint
      const response = await request.post(`${BASE_URL}/api/auth/mfa`, {
        data: { token: '123456' },
      });

      // Then: Should return 401 Unauthorized
      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Unauthorized');
      expect(body.traceId).toBeDefined();
    });

    test('[P0] [MFA-API-002] should reject request with missing token', async ({ request }) => {
      // Given: Authenticated session (simulated via cookies/storage in real scenario)
      // Note: This test assumes auth middleware is bypassed for testing
      // When: POST without MFA token in body
      const response = await request.post(`${BASE_URL}/api/auth/mfa`, {
        data: {},
        headers: { 'Authorization': 'Bearer valid-session-token' },
      });

      // Then: Should return 400 Bad Request
      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body.error).toBe('Bad Request');
      expect(body.message).toContain('MFA token is required');
      expect(body.traceId).toBeDefined();
    });

    test('[P0] [MFA-API-003] should reject invalid MFA token format', async ({ request }) => {
      // When: POST with invalid token format
      const response = await request.post(`${BASE_URL}/api/auth/mfa`, {
        data: { token: 'not-a-number' },
        headers: { 'Authorization': 'Bearer valid-session-token' },
      });

      // Then: Should reject as invalid
      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Unauthorized');
      expect(body.traceId).toBeDefined();
    });

    test('[P1] [MFA-API-004] should reject expired MFA token', async ({ request }) => {
      // When: POST with expired/used token
      const response = await request.post(`${BASE_URL}/api/auth/mfa`, {
        data: { token: '000000' },
        headers: { 'Authorization': 'Bearer valid-session-token' },
      });

      // Then: Should return 401
      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Unauthorized');
      expect(body.message).toMatch(/invalid|expired/i);
    });
  });

  // ==========================================
  // GET /api/auth/mfa/status - MFA Status
  // ==========================================
  
  test.describe('GET /api/auth/mfa/status', () => {
    test('[P0] [MFA-API-005] should reject unauthenticated requests', async ({ request }) => {
      // Given: No authentication
      // When: GET MFA status
      const response = await request.get(`${BASE_URL}/api/auth/mfa/status`);

      // Then: Should return 401
      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Unauthorized');
      expect(body.traceId).toBeDefined();
    });

    test('[P0] [MFA-API-006] should return MFA status for authenticated user', async ({ request }) => {
      // Given: Authenticated user
      // When: GET MFA status
      const response = await request.get(`${BASE_URL}/api/auth/mfa/status`, {
        headers: { 'Authorization': 'Bearer valid-session-token' },
      });

      // Then: Should return status object
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.success).toBe(true);
      expect(body.status).toBeDefined();
      expect(typeof body.status.enabled).toBe('boolean');
      expect(body.traceId).toBeDefined();
    });

    test('[P1] [MFA-API-007] should return 404 for non-existent user', async ({ request }) => {
      // Given: Valid token but user deleted
      // When: GET MFA status
      const response = await request.get(`${BASE_URL}/api/auth/mfa/status`, {
        headers: { 'Authorization': 'Bearer token-for-deleted-user' },
      });

      // Then: Should return 404
      expect(response.status()).toBe(404);
      const body = await response.json();
      expect(body.error).toBe('Not Found');
      expect(body.traceId).toBeDefined();
    });
  });

  // ==========================================
  // POST /api/auth/mfa/setup - MFA Setup
  // ==========================================
  
  test.describe('POST /api/auth/mfa/setup', () => {
    test('[P0] [MFA-API-008] should initiate MFA setup for authenticated user', async ({ request }) => {
      // Given: Authenticated user without MFA
      // When: POST to setup endpoint
      const response = await request.post(`${BASE_URL}/api/auth/mfa/setup`, {
        headers: { 'Authorization': 'Bearer valid-session-token' },
      });

      // Then: Should return setup information
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.success).toBe(true);
      expect(body.secret).toBeDefined();
      expect(body.qrCodeUrl).toBeDefined();
      expect(body.backupCodes).toBeDefined();
      expect(Array.isArray(body.backupCodes)).toBe(true);
      expect(body.backupCodes.length).toBeGreaterThan(0);
    });

    test('[P0] [MFA-API-009] should reject setup for already-enabled MFA', async ({ request }) => {
      // Given: Authenticated user with MFA already enabled
      // When: POST to setup endpoint
      const response = await request.post(`${BASE_URL}/api/auth/mfa/setup`, {
        headers: { 'Authorization': 'Bearer token-for-mfa-enabled-user' },
      });

      // Then: Should return conflict error
      expect(response.status()).toBe(409);
      const body = await response.json();
      expect(body.error).toContain('already enabled');
    });

    test('[P1] [MFA-API-010] should reject unauthenticated setup attempts', async ({ request }) => {
      // When: POST without authentication
      const response = await request.post(`${BASE_URL}/api/auth/mfa/setup`);

      // Then: Should return 401
      expect(response.status()).toBe(401);
    });
  });

  // ==========================================
  // POST /api/auth/mfa/disable - MFA Disable
  // ==========================================
  
  test.describe('POST /api/auth/mfa/disable', () => {
    test('[P0] [MFA-API-011] should disable MFA with valid verification', async ({ request }) => {
      // Given: Authenticated user with MFA enabled
      // When: POST to disable with valid token
      const response = await request.post(`${BASE_URL}/api/auth/mfa/disable`, {
        data: { token: 'valid-mfa-token', confirm: true },
        headers: { 'Authorization': 'Bearer valid-session-token' },
      });

      // Then: Should successfully disable
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.success).toBe(true);
      expect(body.message).toContain('disabled');
    });

    test('[P0] [MFA-API-012] should require confirmation for MFA disable', async ({ request }) => {
      // Given: Authenticated user with MFA enabled
      // When: POST to disable without confirmation flag
      const response = await request.post(`${BASE_URL}/api/auth/mfa/disable`, {
        data: { token: 'valid-mfa-token' },
        headers: { 'Authorization': 'Bearer valid-session-token' },
      });

      // Then: Should require confirmation
      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body.error).toContain('confirm');
    });
  });
});
