/**
 * Policy Config API Tests - Enhanced with @seontechnologies/playwright-utils
 *
 * Demonstrates standardization on apiRequest() helper for consistent:
 * - Schema validation
 * - Retry logic
 * - Error handling
 * - Type safety
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P0 (Critical) - Policy config affects all decisions
 *
 * Tags:
 * - @p0: Critical path (policy config affects all users)
 * - @api: API tests
 * - @policy: Policy domain tests
 * - @config: Configuration tests
 * - @regression: Run in regression suite
 * - @playwright-utils: Uses @seontechnologies/playwright-utils
 */

import { test, expect } from '../support/merged-fixtures';
import { z } from 'zod';

/**
 * Zod schema for Policy Config validation
 * Ensures type safety and API contract validation
 */
const PolicyConfigSchema = z.object({
  hardStopEnabled: z.boolean(),
  dailyLossLimit: z.number(),
  consecutiveLosses: z.number(),
  bankrollPercent: z.number(),
  confidenceThreshold: z.number(),
  edgeThreshold: z.number(),
  driftThreshold: z.number(),
  updatedAt: z.string().datetime().optional(),
  traceId: z.string().optional(),
});

const PolicyConfigResponseSchema = z.object({
  config: PolicyConfigSchema,
  traceId: z.string(),
  timestamp: z.string().datetime(),
});

test.describe('Policy Config API - Enhanced @p0 @api @policy @config @regression @playwright-utils', () => {
  test('@p0 @policy:config:get should retrieve policy config with schema validation', async ({ apiRequest }) => {
    const { status, body, responseTime } = await apiRequest({
      method: 'GET',
      path: '/api/v1/policy/config',
    });

    expect(status).toBe(200);
    expect(body).toBeDefined();
    expect(body.config).toBeDefined();

    const result = PolicyConfigResponseSchema.safeParse(body);
    expect(result.success).toBe(true);

    expect(body.config.hardStopEnabled).toBeTypeOf('boolean');
    expect(body.config.dailyLossLimit).toBeTypeOf('number');
    expect(body.config.consecutiveLosses).toBeTypeOf('number');
    expect(body.traceId).toBeDefined();
    expect(responseTime).toBeLessThan(500);
  });

  test('@p0 @policy:config:put should update policy config', async ({ apiRequest, authToken }) => {
    const newConfig = {
      hardStopEnabled: true,
      dailyLossLimit: 1000,
      consecutiveLosses: 5,
      bankrollPercent: 20,
      confidenceThreshold: 0.75,
      edgeThreshold: 0.05,
      driftThreshold: 0.15,
    };

    const { status, body, traceId } = await apiRequest({
      method: 'PUT',
      path: '/api/v1/policy/config',
      data: newConfig,
      headers: {
        Authorization: `Bearer ${authToken}`,
      },
    });

    expect(status).toBe(200);
    expect(body.config.dailyLossLimit).toBe(newConfig.dailyLossLimit);
    expect(traceId).toBeDefined();
  });

  test('@p1 @policy:config:error should reject invalid config values', async ({ apiRequest, authToken }) => {
    const invalidConfig = {
      hardStopEnabled: true,
      dailyLossLimit: -100,
      consecutiveLosses: 100,
      bankrollPercent: 150,
      confidenceThreshold: 2.0,
      edgeThreshold: -0.1,
      driftThreshold: 0.5,
    };

    const { status, body } = await apiRequest({
      method: 'PUT',
      path: '/api/v1/policy/config',
      data: invalidConfig,
      headers: {
        Authorization: `Bearer ${authToken}`,
      },
      expectStatus: [400, 422],
    });

    expect([400, 422]).toContain(status);
    expect(body.error).toBeDefined();
  });

  test('@p0 @policy:config:auth should reject unauthenticated requests', async ({ apiRequest }) => {
    const { status, body } = await apiRequest({
      method: 'GET',
      path: '/api/v1/policy/config',
      expectStatus: [401, 403],
    });

    expect([401, 403]).toContain(status);
    expect(body.error).toBeDefined();
  });
});

/**
 * Test execution commands:
 * Run all policy config tests: npx playwright test tests/api/policy-config-enhanced.spec.ts
 * Run P0 tests only: npm run test:p0 -- tests/api/policy-config-enhanced.spec.ts
 * Run with playwright-utils tag: npx playwright test --grep @playwright-utils
 */
