/**
 * User Profile API Tests
 * Tests for /api/auth/me endpoint
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P1
 * Test IDs: PROFILE-API-001 through PROFILE-API-006
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

test.describe('User Profile API Tests @api @profile @auth', () => {
  // ==========================================
  // GET /api/auth/me - Get Current User
  // ==========================================
  
  test.describe('GET /api/auth/me', () => {
    test('[P0] [PROFILE-API-001] should return user profile with valid token', async ({ request }) => {
      // Given: Valid bearer token
      const validToken = 'token-valid-user-123';
      
      // When: GET /api/auth/me
      const response = await request.get(`${BASE_URL}/api/auth/me`, {
        headers: { 'Authorization': `Bearer ${validToken}` },
      });

      // Then: Should return user profile
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.id).toBeDefined();
      expect(body.email).toBeDefined();
      expect(body.role).toBeDefined();
    });

    test('[P0] [PROFILE-API-002] should reject requests without authorization header', async ({ request }) => {
      // When: GET without Authorization header
      const response = await request.get(`${BASE_URL}/api/auth/me`);

      // Then: Should return 401
      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Unauthorized');
    });

    test('[P0] [PROFILE-API-003] should reject malformed authorization header', async ({ request }) => {
      // When: GET with malformed header (not Bearer)
      const response = await request.get(`${BASE_URL}/api/auth/me`, {
        headers: { 'Authorization': 'Basic dXNlcjpwYXNz' },
      });

      // Then: Should return 401
      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Unauthorized');
    });

    test('[P0] [PROFILE-API-004] should reject invalid token format', async ({ request }) => {
      // When: GET with invalid token format
      const response = await request.get(`${BASE_URL}/api/auth/me`, {
        headers: { 'Authorization': 'Bearer invalid-token-format' },
      });

      // Then: Should return 401
      expect(response.status()).toBe(401);
      const body = await response.json();
      expect(body.error).toBe('Invalid token');
    });

    test('[P1] [PROFILE-API-005] should include MFA status in profile', async ({ request }) => {
      // Given: User with MFA enabled
      const token = 'token-mfa-enabled-user';
      
      // When: GET profile
      const response = await request.get(`${BASE_URL}/api/auth/me`, {
        headers: { 'Authorization': `Bearer ${token}` },
      });

      // Then: Should include MFA status
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.mfaEnabled).toBeDefined();
    });

    test('[P2] [PROFILE-API-006] should handle token with special characters', async ({ request }) => {
      // When: GET with token containing special characters
      const response = await request.get(`${BASE_URL}/api/auth/me`, {
        headers: { 'Authorization': 'Bearer token-with-!@#$%^&*()' },
      });

      // Then: Should handle gracefully (either 200 if valid or 401 if invalid)
      expect([200, 401]).toContain(response.status());
    });
  });
});
