/**
 * Role Change API Integration Tests
 * Tests for PUT /api/v1/admin/users/[id]/role
 *
 * Generated by BMAD code-review workflow
 * Priority: P0 (Critical)
 */

import { test, expect } from "@playwright/test";

test.describe("Role Change API - Authentication & Authorization @api @rbac @security", () => {
  test("[P0] should reject request without authentication", async ({ request }) => {
    // Given no authentication
    // When attempting role change
    const response = await request.put("/api/v1/admin/users/user-123/role", {
      data: { role: "support" },
    });

    // Then should return 401
    expect(response.status()).toBe(401);
    const body = await response.json();
    expect(body.error.code).toBe("UNAUTHORIZED");
    expect(body.meta.traceId).toBeDefined();
  });

  test("[P0] should reject non-admin users", async ({ request }) => {
    // Given regular user token (would need to be set up in auth)
    // This test assumes we have a way to get a user token
    const response = await request.put("/api/v1/admin/users/user-123/role", {
      data: { role: "support" },
      headers: {
        // In real test, would include valid non-admin session cookie
        Cookie: "invalid-session",
      },
    });

    // Should be unauthorized
    expect([401, 403]).toContain(response.status());
  });
});

test.describe("Role Change API - Self-Demotion Protection @api @rbac @security", () => {
  test("[P0] should prevent admin from self-demotion", async ({ request }) => {
    // Given admin user trying to change own role
    // This is a critical security test
    const adminUserId = "admin-user-id";

    const response = await request.put(`/api/v1/admin/users/${adminUserId}/role`, {
      data: { role: "ops" },
      headers: {
        // Would include valid admin session
      },
    });

    // Then should return 403 with specific error
    expect(response.status()).toBe(403);
    const body = await response.json();
    expect(body.error.code).toBe("FORBIDDEN");
    expect(body.error.message).toContain("rétrograder");
    expect(body.meta.traceId).toBeDefined();
  });
});

test.describe("Role Change API - Validation @api @rbac @validation", () => {
  test("[P0] should reject invalid role values", async ({ request }) => {
    // Given invalid role value
    const response = await request.put("/api/v1/admin/users/user-123/role", {
      data: { role: "superadmin" }, // Invalid role
      headers: {
        // Would include valid admin session
      },
    });

    // Then should return 400
    expect(response.status()).toBe(400);
    const body = await response.json();
    expect(body.error.code).toBe("VALIDATION_ERROR");
    expect(body.meta.traceId).toBeDefined();
  });

  test("[P1] should reject request without role field", async ({ request }) => {
    const response = await request.put("/api/v1/admin/users/user-123/role", {
      data: {}, // Missing role
      headers: {
        // Would include valid admin session
      },
    });

    expect(response.status()).toBe(400);
    const body = await response.json();
    expect(body.error.code).toBe("VALIDATION_ERROR");
  });

  test("[P1] should reject request with non-existent user", async ({ request }) => {
    const response = await request.put("/api/v1/admin/users/non-existent-id/role", {
      data: { role: "support" },
      headers: {
        // Would include valid admin session
      },
    });

    expect(response.status()).toBe(404);
    const body = await response.json();
    expect(body.error.code).toBe("NOT_FOUND");
    expect(body.meta.traceId).toBeDefined();
  });
});

test.describe("Role Change API - Success Cases @api @rbac @happy-path", () => {
  test("[P0] should successfully change role with valid data", async ({ request }) => {
    // Given valid admin and target user
    const targetUserId = "user-to-change";

    const response = await request.put(`/api/v1/admin/users/${targetUserId}/role`, {
      data: { role: "support" },
      headers: {
        // Would include valid admin session
      },
    });

    // Then should return 200 with updated data
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.data.role).toBe("support");
    expect(body.data.userId).toBe(targetUserId);
    expect(body.data.updatedAt).toBeDefined();
    expect(body.meta.traceId).toBeDefined();
    expect(body.meta.timestamp).toBeDefined();
  });

  test("[P1] should persist role change to database", async ({ request }) => {
    // Given role change request
    const targetUserId = "user-to-verify";

    await request.put(`/api/v1/admin/users/${targetUserId}/role`, {
      data: { role: "ops" },
      headers: {
        // Would include valid admin session
      },
    });

    // When fetching user data via GET
    const getResponse = await request.get(`/api/v1/admin/users/${targetUserId}/role`, {
      headers: {
        // Would include valid admin session
      },
    });

    // Then role should be persisted
    const body = await getResponse.json();
    expect(body.data.role).toBe("ops");
  });
});

test.describe("Role Change API - Audit Logging @api @rbac @audit", () => {
  test("[P0] should create audit log entry on role change", async ({ request }) => {
    // Given successful role change
    const targetUserId = "user-audit-test";
    const oldRole = "user";
    const newRole = "support";

    await request.put(`/api/v1/admin/users/${targetUserId}/role`, {
      data: { role: newRole },
      headers: {
        // Would include valid admin session
      },
    });

    // Then audit log should exist
    // In real test, would query database directly
    // For now, we verify the API contract includes traceId
    const response = await request.put(`/api/v1/admin/users/${targetUserId}/role`, {
      data: { role: "ops" },
      headers: {
        // Would include valid admin session
      },
    });

    const body = await response.json();
    expect(body.meta.traceId).toBeDefined();
  });
});

test.describe("Role Change API - Rate Limiting @api @rbac @rate-limit", () => {
  test("[P1] should rate limit excessive role changes", async ({ request }) => {
    // Given many rapid role change attempts
    const targetUserId = "user-rate-limit-test";

    // Make 15 requests (limit is 10 per minute)
    const requests = Array(15).fill(null).map(() =>
      request.put(`/api/v1/admin/users/${targetUserId}/role`, {
        data: { role: "support" },
        headers: {
          // Would include valid admin session
        },
      })
    );

    const responses = await Promise.all(requests);

    // Some should be rate limited (429)
    const rateLimitedCount = responses.filter(r => r.status() === 429).length;
    expect(rateLimitedCount).toBeGreaterThan(0);
  });
});

test.describe("Role Change API - Response Format @api @rbac @contract", () => {
  test("[P1] should return correct error response format per architecture", async ({ request }) => {
    // When making invalid request
    const response = await request.put("/api/v1/admin/users/invalid-id/role", {
      data: { role: "invalid" },
    });

    const body = await response.json();

    // Then should follow architecture error format §299-303
    expect(body).toHaveProperty("error");
    expect(body.error).toHaveProperty("code");
    expect(body.error).toHaveProperty("message");
    expect(body).toHaveProperty("meta");
    expect(body.meta).toHaveProperty("traceId");
    expect(body.meta).toHaveProperty("timestamp");
  });
});
