import { test, expect } from '@playwright/test';
import { createUser } from '../test-utils/factories';

/**
 * Runs/Daily Runs API Tests - Coverage Expansion
 * Generated by BMAD testarch-automate workflow
 *
 * Tags: @p0 @p1 @runs @daily-run @api
 */

test.describe('Runs API @runs @api', () => {
  const baseUrl = process.env.BASE_URL || 'http://localhost:3000';

  async function getAuthToken(request: any) {
    const user = createUser({ password: 'SecurePass123!' });
    await request.post(`${baseUrl}/api/auth/register`, {
      data: { email: user.email, password: user.password, name: user.name },
    });
    const loginRes = await request.post(`${baseUrl}/api/auth/login`, {
      data: { email: user.email, password: user.password },
    });
    const { token } = await loginRes.json();
    return token;
  }

  test.describe('GET /api/v1/runs @p1', () => {
    test('[P1] should list all runs for authenticated user', async ({ request }) => {
      const token = await getAuthToken(request);

      const response = await request.get(`${baseUrl}/api/v1/runs`, {
        headers: { Authorization: `Bearer ${token}` },
      });

      expect([200, 401]).toContain(response.status());
      if (response.status() === 200) {
        const body = await response.json();
        expect(Array.isArray(body)).toBe(true);
      }
    });

    test('[P2] should support pagination parameters', async ({ request }) => {
      const token = await getAuthToken(request);

      const response = await request.get(`${baseUrl}/api/v1/runs?limit=10&offset=0`, {
        headers: { Authorization: `Bearer ${token}` },
      });

      expect([200, 401]).toContain(response.status());
    });
  });

  test.describe('GET /api/v1/runs/:id @p1', () => {
    test('[P1] should return specific run details', async ({ request }) => {
      const token = await getAuthToken(request);

      const response = await request.get(`${baseUrl}/api/v1/runs/run-123`, {
        headers: { Authorization: `Bearer ${token}` },
      });

      expect([200, 401, 404]).toContain(response.status());
    });
  });

  test.describe('POST /api/v1/runs/trigger @p0', () => {
    test('[P0] should trigger new run for authorized user', async ({ request }) => {
      const token = await getAuthToken(request);

      const response = await request.post(`${baseUrl}/api/v1/runs/trigger`, {
        headers: { Authorization: `Bearer ${token}` },
        data: {
          type: 'daily',
          force: false,
        },
      });

      expect([200, 202, 401, 403]).toContain(response.status());
      if (response.status() === 200 || response.status() === 202) {
        const body = await response.json();
        expect(body.runId).toBeDefined();
      }
    });

    test('[P1] should reject unauthorized trigger attempts', async ({ request }) => {
      const response = await request.post(`${baseUrl}/api/v1/runs/trigger`, {
        data: { type: 'daily' },
      });

      expect(response.status()).toBe(401);
    });
  });

  test.describe('GET /api/v1/runs/health @p0', () => {
    test('[P0] should return runs system health', async ({ request }) => {
      const response = await request.get(`${baseUrl}/api/v1/runs/health`);

      expect([200, 401]).toContain(response.status());
      if (response.status() === 200) {
        const body = await response.json();
        expect(body.status).toBeDefined();
        expect(body.lastRun).toBeDefined();
      }
    });
  });
});