/**
 * Test Fixtures - Authentication
 * 
 * Provides authentication fixtures for API and E2E tests
 * Generated by BMAD TEA (testarch-automate workflow)
 */

import { test as base, Page, APIRequestContext } from '@playwright/test';
import { faker } from '@faker-js/faker';

const BASE_URL = process.env.E2E_BASE_URL || 'http://localhost:3000';
const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';

/**
 * Extended test type with custom fixtures
 */
export const test = base.extend<{
  authenticatedUser: Page;
  authenticatedAdminUser: Page;
  authToken: string;
  adminAuthToken: string;
  policyHardstopStatus: () => Promise<{
    isActive: boolean;
    triggeredAt: string | null;
    reason: string | null;
  }>;
  redisHealthCheck: () => Promise<{
    status: string;
    latencyMs: number;
    connectedClients?: number;
    usedMemory?: string;
  }>;
}>({
  /**
   * Authenticated regular user fixture
   * Logs in as a standard user before each test
   */
  authenticatedUser: async ({ page }, use) => {
    const userEmail = process.env.TEST_USER_EMAIL || faker.internet.email();
    const userPassword = process.env.TEST_USER_PASSWORD || 'TestPassword123!';
    
    await page.goto(`${BASE_URL}/login`);
    await page.fill('[data-testid="email"]', userEmail);
    await page.fill('[data-testid="password"]', userPassword);
    await page.click('[data-testid="login-button"]');
    await page.waitForURL(/.*dashboard/);
    
    await use(page);
  },

  /**
   * Authenticated admin user fixture
   * Logs in as an admin before each test
   */
  authenticatedAdminUser: async ({ page }, use) => {
    const adminEmail = process.env.TEST_ADMIN_EMAIL || 'admin@example.com';
    const adminPassword = process.env.TEST_ADMIN_PASSWORD || 'AdminPassword123!';
    
    await page.goto(`${BASE_URL}/login`);
    await page.fill('[data-testid="email"]', adminEmail);
    await page.fill('[data-testid="password"]', adminPassword);
    await page.click('[data-testid="login-button"]');
    await page.waitForURL(/.*dashboard/);
    
    await use(page);
  },

  /**
   * Auth token for API tests (regular user)
   */
  authToken: async ({ request }, use) => {
    const userEmail = process.env.TEST_USER_EMAIL || faker.internet.email();
    const userPassword = process.env.TEST_USER_PASSWORD || 'TestPassword123!';
    
    const response = await request.post(`${API_BASE_URL}/api/auth/login`, {
      data: {
        email: userEmail,
        password: userPassword,
      },
    });
    
    if (response.status() === 200) {
      const body = await response.json();
      await use(body.token || '');
    } else {
      await use('');
    }
  },

  /**
   * Admin auth token for API tests
   */
  adminAuthToken: async ({ request }, use) => {
    const adminEmail = process.env.TEST_ADMIN_EMAIL || 'admin@example.com';
    const adminPassword = process.env.TEST_ADMIN_PASSWORD || 'AdminPassword123!';
    
    const response = await request.post(`${API_BASE_URL}/api/auth/login`, {
      data: {
        email: adminEmail,
        password: adminPassword,
      },
    });
    
    if (response.status() === 200) {
      const body = await response.json();
      await use(body.token || '');
    } else {
      await use('');
    }
  },

  /**
   * Get current hardstop policy status
   */
  policyHardstopStatus: async ({ request }, use) => {
    const getStatus = async () => {
      const response = await request.get(`${API_BASE_URL}/api/v1/policy/hardstop/status`);
      const body = await response.json();
      return body;
    };
    await use(getStatus);
  },

  /**
   * Check Redis health status
   */
  redisHealthCheck: async ({ request }, use) => {
    const checkHealth = async () => {
      const response = await request.get(`${API_BASE_URL}/api/health/redis`);
      const body = await response.json();
      return body;
    };
    await use(checkHealth);
  },
});

export { expect } from '@playwright/test';
