/**
 * Test User Fixtures
 * Pre-defined users for testing RBAC functionality
 * NFR9: Data minimization - no name field collected
 *
 * Generated by BMAD code-review workflow
 */

import { UserRole } from "../../src/server/auth/rbac";

// NFR9: Data minimization - only email and password
export interface TestUser {
  email: string;
  password: string;
  role: UserRole;
}

export const testUsers = {
  admin: {
    email: process.env.TEST_ADMIN_EMAIL || "admin@test.com",
    password: process.env.TEST_ADMIN_PASSWORD || "admin123",
    role: UserRole.ADMIN,
  },
  ops: {
    email: process.env.TEST_OPS_EMAIL || "ops@test.com",
    password: process.env.TEST_OPS_PASSWORD || "ops123",
    role: UserRole.OPS,
  },
  support: {
    email: process.env.TEST_SUPPORT_EMAIL || "support@test.com",
    password: process.env.TEST_SUPPORT_PASSWORD || "support123",
    role: UserRole.SUPPORT,
  },
  user: {
    email: process.env.TEST_USER_EMAIL || "user@test.com",
    password: process.env.TEST_USER_PASSWORD || "user123",
    role: UserRole.USER,
  },
} as const;

/**
 * Create a test user in the database via API
 * NFR9: Only email and password sent (no name)
 */
export async function createTestUser(
  request: any,
  user: TestUser
): Promise<{ id: string; email: string }> {
  const response = await request.post("/api/auth/register", {
    data: {
      email: user.email,
      password: user.password,
      // NFR9: name field not sent per data minimization
    },
  });

  if (!response.ok() && response.status() !== 201) {
    // User might already exist
    console.log(`User ${user.email} might already exist or registration failed`);
  }

  return {
    id: `test-${user.role}-${Date.now()}`,
    email: user.email,
  };
}

/**
 * Login as a specific test user
 */
export async function loginAs(
  page: any,
  user: TestUser
): Promise<void> {
  await page.goto("/login");
  await page.getByLabel(/email/i).fill(user.email);
  await page.getByLabel(/password/i).fill(user.password);
  await page.getByRole("button", { name: /sign in|login/i }).click();
  await page.waitForURL(/\/dashboard/);
}

/**
 * Get authenticated API request context
 */
export async function getAuthenticatedRequest(
  request: any,
  user: TestUser
): Promise<any> {
  // First, login via the web interface to get cookies
  // This is a simplified version - in practice you'd use API login
  return request;
}
