/**
 * Merged Fixtures
 * Project fixtures for NBA Analyst
 *
 * Enhanced with @seontechnologies/playwright-utils
 * for advanced API testing patterns
 *
 * Generated by BMAD testarch-framework workflow
 * Updated: 2026-02-15
 */

import { test as base, expect } from '@playwright/test';
import type { APIRequestContext } from '@playwright/test';

// Import factories
import { createUser, createDecision, createRun, createMatch, createAdminUser } from './factories';
import type { User, Decision, Run, Match } from './factories';

// Import playwright-utils helpers (direct functions, not fixtures)
import { apiRequest as apiRequestUtil } from '@seontechnologies/playwright-utils/api-request';

/**
 * Custom fixtures type definitions
 */
type CustomFixtures = {
  testUser: User;
  adminUser: User;
  testDecision: Decision;
  testRun: Run;
  dbHelpers: {
    seedUser: (overrides?: Partial<User>) => User;
    seedDecision: (overrides?: Partial<Decision>) => Decision;
    seedRun: (overrides?: Partial<Run>) => Run;
    seedMatch: (overrides?: Partial<Match>) => Match;
  };
  api: {
    request: APIRequestContext;
    baseUrl: string;
    get: (path: string, headers?: Record<string, string>) => Promise<Response>;
    post: (path: string, data: unknown, headers?: Record<string, string>) => Promise<Response>;
  };
  apiRequest: typeof apiRequestUtil;
  authToken: string;
};

/**
 * Extended test with custom fixtures
 */
export const test = base.extend<CustomFixtures>({
  // Custom fixture: Auto-seeded test user
  testUser: async ({}, use) => {
    const user = createUser({ role: 'user' });
    await use(user);
  },

  // Custom fixture: Admin user
  adminUser: async ({}, use) => {
    const admin = createAdminUser();
    await use(admin);
  },

  // Custom fixture: Test decision
  testDecision: async ({}, use) => {
    const decision = createDecision({ status: 'Pick' });
    await use(decision);
  },

  // Custom fixture: Test run
  testRun: async ({}, use) => {
    const run = createRun({ status: 'completed' });
    await use(run);
  },

  // Custom fixture: Database helpers
  dbHelpers: async ({}, use) => {
    await use({
      seedUser: (overrides = {}) => createUser(overrides),
      seedDecision: (overrides = {}) => createDecision(overrides),
      seedRun: (overrides = {}) => createRun(overrides),
      seedMatch: (overrides = {}) => createMatch(overrides),
    });
  },

  // Custom fixture: Legacy API helper (backward compatibility)
  api: async ({ request }, use) => {
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    await use({
      request,
      baseUrl,
      get: async (path: string, headers = {}) => {
        return request.get(`${baseUrl}${path}`, { headers });
      },
      post: async (path: string, data: unknown, headers = {}) => {
        return request.post(`${baseUrl}${path}`, {
          data,
          headers: { 'Content-Type': 'application/json', ...headers },
        });
      },
    });
  },

  // Custom fixture: apiRequest wrapper using playwright-utils
  apiRequest: async ({ request }, use) => {
    await use((options: any) => apiRequestUtil({ request, ...options }));
  },

  // Custom fixture: authToken
  authToken: async ({ request }, use) => {
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    const loginResponse = await request.post(`${baseUrl}/api/auth/login`, {
      data: {
        email: process.env.TEST_ADMIN_EMAIL || 'admin@example.com',
        password: process.env.TEST_ADMIN_PASSWORD || 'AdminPassword123!',
      },
    });

    if (loginResponse.ok()) {
      const body = await loginResponse.json();
      await use(body.token || '');
    } else {
      await use('');
    }
  },
});

export { expect } from '@playwright/test';

/**
 * Available fixtures in merged-fixtures:
 *
 * - apiRequest: Typed HTTP client with schema validation and retry
 * - authToken: Authentication token for API requests
 * - testUser: Factory-generated user data
 * - adminUser: Factory-generated admin user
 * - testDecision: Factory-generated decision
 * - testRun: Factory-generated run
 * - dbHelpers: Database seeding helpers
 * - api: Legacy API helper (backward compatible)
 */
