/**
 * Merged Fixtures
 * Project fixtures for NBA Analyst
 *
 * Generated by BMAD testarch-framework workflow
 * Note: Simplified version without @seontechnologies/playwright-utils
 * Install the package later for advanced utilities
 */

import { test as base, expect } from '@playwright/test';

// Import custom fixtures
import { createUser, createDecision, createRun, createMatch } from './factories';

// Extend base test with custom fixtures
export const test = base.extend({
  // Custom fixture 1: Auto-seeded test user
  testUser: async ({ request }, use) => {
    const user = createUser({ role: 'user' });
    await use(user);
  },

  // Custom fixture 2: Admin user
  adminUser: async ({ request }, use) => {
    const admin = createUser({ role: 'admin' });
    await use(admin);
  },

  // Custom fixture 3: Test decision
  testDecision: async ({ request }, use) => {
    const decision = createDecision({ status: 'Pick' });
    await use(decision);
  },

  // Custom fixture 4: Test run
  testRun: async ({ request }, use) => {
    const run = createRun({ status: 'completed' });
    await use(run);
  },

  // Custom fixture 5: Database helpers
  dbHelpers: async ({ request }, use) => {
    await use({
      seedUser: (overrides = {}) => createUser(overrides),
      seedDecision: (overrides = {}) => createDecision(overrides),
      seedRun: (overrides = {}) => createRun(overrides),
      seedMatch: (overrides = {}) => createMatch(overrides),
    });
  },

  // Custom fixture 6: API helper
  api: async ({ request }, use) => {
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    await use({
      request,
      baseUrl,
      get: async (path: string, headers = {}) => {
        return request.get(`${baseUrl}${path}`, { headers });
      },
      post: async (path: string, data: unknown, headers = {}) => {
        return request.post(`${baseUrl}${path}`, {
          data,
          headers: { 'Content-Type': 'application/json', ...headers },
        });
      },
    });
  },
});

export { expect } from '@playwright/test';
