/**
 * RBAC Unit Tests
 * Unit tests for Role-Based Access Control functions
 *
 * Generated by BMAD testarch-automate workflow
 * Priority: P1 (High)
 */

import { test, expect, describe } from 'vitest';
import {
  hasRole,
  isAdmin,
  isOps,
  UserRole,
  ALL_ROLES,
  ROLE_HIERARCHY,
} from '../../src/server/auth/rbac';

describe('RBAC - hasRole @unit @rbac @security', () => {
  test('[P0] [1.6-RBAC-001] should return true when user has exact required role', () => {
    expect(hasRole(UserRole.ADMIN, UserRole.ADMIN)).toBe(true);
  });

  test('[P0] [1.6-RBAC-002] should return true when user has higher role in hierarchy', () => {
    expect(hasRole(UserRole.ADMIN, UserRole.OPS)).toBe(true);
  });

  test('[P0] [1.6-RBAC-003] should return false when user has lower role in hierarchy', () => {
    expect(hasRole(UserRole.USER, UserRole.ADMIN)).toBe(false);
  });

  test('[P1] [1.6-RBAC-004] should handle support role correctly', () => {
    expect(hasRole(UserRole.SUPPORT, UserRole.USER)).toBe(true);
    expect(hasRole(UserRole.SUPPORT, UserRole.SUPPORT)).toBe(true);
    expect(hasRole(UserRole.SUPPORT, UserRole.OPS)).toBe(false);
    expect(hasRole(UserRole.SUPPORT, UserRole.ADMIN)).toBe(false);
  });

  test('[P1] [1.6-RBAC-005] should handle ops role correctly', () => {
    expect(hasRole(UserRole.OPS, UserRole.USER)).toBe(true);
    expect(hasRole(UserRole.OPS, UserRole.SUPPORT)).toBe(true);
    expect(hasRole(UserRole.OPS, UserRole.OPS)).toBe(true);
    expect(hasRole(UserRole.OPS, UserRole.ADMIN)).toBe(false);
  });

  test('[P1] [1.6-RBAC-006] should verify role hierarchy order', () => {
    expect(hasRole(UserRole.USER, UserRole.USER)).toBe(true);
    expect(hasRole(UserRole.SUPPORT, UserRole.USER)).toBe(true);
    expect(hasRole(UserRole.OPS, UserRole.USER)).toBe(true);
    expect(hasRole(UserRole.ADMIN, UserRole.USER)).toBe(true);

    expect(hasRole(UserRole.USER, UserRole.SUPPORT)).toBe(false);
    expect(hasRole(UserRole.SUPPORT, UserRole.SUPPORT)).toBe(true);
    expect(hasRole(UserRole.OPS, UserRole.SUPPORT)).toBe(true);
    expect(hasRole(UserRole.ADMIN, UserRole.SUPPORT)).toBe(true);

    expect(hasRole(UserRole.USER, UserRole.OPS)).toBe(false);
    expect(hasRole(UserRole.SUPPORT, UserRole.OPS)).toBe(false);
    expect(hasRole(UserRole.OPS, UserRole.OPS)).toBe(true);
    expect(hasRole(UserRole.ADMIN, UserRole.OPS)).toBe(true);

    expect(hasRole(UserRole.USER, UserRole.ADMIN)).toBe(false);
    expect(hasRole(UserRole.SUPPORT, UserRole.ADMIN)).toBe(false);
    expect(hasRole(UserRole.OPS, UserRole.ADMIN)).toBe(false);
    expect(hasRole(UserRole.ADMIN, UserRole.ADMIN)).toBe(true);
  });
});

describe('RBAC - isAdmin @unit @rbac @security', () => {
  test('[P0] [1.6-RBAC-007] should return true for admin role', () => {
    expect(isAdmin(UserRole.ADMIN)).toBe(true);
  });

  test('[P0] [1.6-RBAC-008] should return false for non-admin roles', () => {
    expect(isAdmin(UserRole.USER)).toBe(false);
    expect(isAdmin(UserRole.SUPPORT)).toBe(false);
    expect(isAdmin(UserRole.OPS)).toBe(false);
  });
});

describe('RBAC - isOps @unit @rbac @security', () => {
  test('[P0] [1.6-RBAC-009] should return true for ops role', () => {
    expect(isOps(UserRole.OPS)).toBe(true);
  });

  test('[P0] [1.6-RBAC-010] should return true for admin role (admin includes ops)', () => {
    expect(isOps(UserRole.ADMIN)).toBe(true);
  });

  test('[P0] [1.6-RBAC-011] should return false for user and support roles', () => {
    expect(isOps(UserRole.USER)).toBe(false);
    expect(isOps(UserRole.SUPPORT)).toBe(false);
  });
});

describe('RBAC Config @unit @rbac @config', () => {
  test('[P1] [1.6-RBAC-012] should define all expected roles', () => {
    expect(ALL_ROLES).toContain(UserRole.USER);
    expect(ALL_ROLES).toContain(UserRole.SUPPORT);
    expect(ALL_ROLES).toContain(UserRole.OPS);
    expect(ALL_ROLES).toContain(UserRole.ADMIN);
    expect(ALL_ROLES).toHaveLength(4);
  });

  test('[P1] [1.6-RBAC-013] should have correct default role', () => {
    expect(ALL_ROLES[0]).toBe(UserRole.USER);
    expect(ALL_ROLES).toContain(UserRole.USER);
  });
});

describe('RBAC Edge Cases @unit @rbac @edge-cases', () => {
  test('[P2] [1.6-RBAC-014] should handle all role combinations', () => {
    const roles: UserRole[] = [UserRole.USER, UserRole.SUPPORT, UserRole.OPS, UserRole.ADMIN];

    for (const userRole of roles) {
      for (const requiredRole of roles) {
        const result = hasRole(userRole, requiredRole);
        const userLevel = ROLE_HIERARCHY[userRole];
        const requiredLevel = ROLE_HIERARCHY[requiredRole];

        // User should have access if their level is >= required level
        expect(result).toBe(userLevel >= requiredLevel);
      }
    }
  });
});
